#!/usr/bin/env bash
# Render deploy/argocd/values/sandbox.yaml from terraform outputs.
# Run after `terraform apply`; commit the result so ArgoCD can read it.
# Endpoints/ARNs only — never secrets.
set -euo pipefail
PROFILE="${AWS_PROFILE:-rtdp-devin}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT/infra/terraform/envs/sandbox"

tfout() { AWS_PROFILE="$PROFILE" terraform output -raw "$1"; }

MSK=$(tfout msk_bootstrap_iam)
AURORA_EP=$(tfout aurora_writer_endpoint)
AURORA_SECRET=$(tfout aurora_master_secret_arn)
VALKEY=$(tfout valkey_endpoint)
ARTIFACTS=$(AWS_PROFILE="$PROFILE" terraform output -json bucket_names | python3 -c 'import json,sys; print(json.load(sys.stdin)["artifacts"])')
BUNDLES=$(AWS_PROFILE="$PROFILE" terraform output -json bucket_names | python3 -c 'import json,sys; print(json.load(sys.stdin)["bundles"])')
TOOLS_IMG=$(grep -oE 'toolsImage: ".*"' "$ROOT/deploy/argocd/values/sandbox.yaml" 2>/dev/null | cut -d'"' -f2)
[ -n "$TOOLS_IMG" ] && [ "$TOOLS_IMG" != "SET_BY_PUSH_IMAGES" ] || TOOLS_IMG="SET_BY_PUSH_IMAGES"

cat > "$ROOT/deploy/argocd/values/sandbox.yaml" <<EOF
# GENERATED by tools/aws/render-env.sh — do not edit by hand.
# Committed so ArgoCD (git-sourced) can resolve it. Endpoints/ARNs only.
env:
  RTDP_KAFKA_AUTH: "iam"
  RTDP_KAFKA_BROKERS: "$MSK"
  RTDP_REDIS_ADDR: "${VALKEY}:6379"
  RTDP_REDIS_TLS: "true"
  RTDP_BUCKET_ARTIFACTS: "$ARTIFACTS"
  RTDP_BUCKET_BUNDLES: "$BUNDLES"
  AWS_REGION: "us-east-1"

bundleSync:
  bucket: "$BUNDLES"                      # merged into the orchestrator app

bootstrap:
  auroraSecretArn: "$AURORA_SECRET"
  auroraEndpoint: "$AURORA_EP"
  databaseName: rtdp
  toolsImage: "$TOOLS_IMG"                # rtdp-tools image digest (push-images.sh)
  kafkaBrokers: "$MSK"
  bundlesBucket: "$BUNDLES"
  artifactsBucket: "$ARTIFACTS"
EOF
echo "[render-env] wrote deploy/argocd/values/sandbox.yaml"
