// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/agent/v1/agent.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.agent.v1;

@com.google.protobuf.Generated
public final class Agent extends com.google.protobuf.GeneratedFile {
  private Agent() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Agent");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_agent_v1_Principal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_agent_v1_Principal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_agent_v1_DelegationLink_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_agent_v1_DelegationLink_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_agent_v1_DelegationChain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_agent_v1_DelegationChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_agent_v1_AgentCall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_agent_v1_AgentCall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031rtdp/agent/v1/agent.proto\022\rrtdp.agent." +
      "v1\032\037google/protobuf/timestamp.proto\"\253\001\n\t" +
      "Principal\0221\n\004kind\030\001 \001(\0162\035.rtdp.agent.v1." +
      "Principal.KindR\004kind\022\016\n\002id\030\002 \001(\tR\002id\022\033\n\t" +
      "tenant_id\030\003 \001(\tR\010tenantId\">\n\004Kind\022\024\n\020KIN" +
      "D_UNSPECIFIED\020\000\022\n\n\006PERSON\020\001\022\007\n\003ORG\020\002\022\013\n\007" +
      "SERVICE\020\003\"\271\002\n\016DelegationLink\022\031\n\010agent_id" +
      "\030\001 \001(\tR\007agentId\022#\n\ragent_version\030\002 \001(\tR\014" +
      "agentVersion\022\035\n\nagent_kind\030\003 \001(\tR\tagentK" +
      "ind\022\026\n\006scopes\030\004 \003(\tR\006scopes\0227\n\tissued_at" +
      "\030\005 \001(\0132\032.google.protobuf.TimestampR\010issu" +
      "edAt\0229\n\nexpires_at\030\006 \001(\0132\032.google.protob" +
      "uf.TimestampR\texpiresAt\022\031\n\010grant_id\030\007 \001(" +
      "\tR\007grantId\022!\n\014max_autonomy\030\010 \001(\tR\013maxAut" +
      "onomy\"\261\001\n\017DelegationChain\0226\n\tprincipal\030\001" +
      " \001(\0132\030.rtdp.agent.v1.PrincipalR\tprincipa" +
      "l\0223\n\005links\030\002 \003(\0132\035.rtdp.agent.v1.Delegat" +
      "ionLinkR\005links\022\024\n\005proof\030\003 \001(\tR\005proof\022\033\n\t" +
      "proof_kid\030\004 \001(\tR\010proofKid\"\250\004\n\tAgentCall\022" +
      "\027\n\007call_id\030\001 \001(\tR\006callId\022*\n\002at\030\002 \001(\0132\032.g" +
      "oogle.protobuf.TimestampR\002at\022\033\n\ttenant_i" +
      "d\030\003 \001(\tR\010tenantId\022 \n\013environment\030\004 \001(\tR\013" +
      "environment\022\027\n\007task_id\030\005 \001(\tR\006taskId\022\030\n\007" +
      "purpose\030\006 \001(\tR\007purpose\022!\n\014principal_id\030\007" +
      " \001(\tR\013principalId\022\031\n\010agent_id\030\010 \001(\tR\007age" +
      "ntId\022#\n\ragent_version\030\t \001(\tR\014agentVersio" +
      "n\022\037\n\013chain_depth\030\n \001(\005R\nchainDepth\022\022\n\004to" +
      "ol\030\013 \001(\tR\004tool\022\030\n\007backend\030\014 \001(\tR\007backend" +
      "\022\030\n\007outcome\030\r \001(\tR\007outcome\022\037\n\013decision_i" +
      "d\030\016 \001(\tR\ndecisionId\022\035\n\nlatency_ms\030\017 \001(\003R" +
      "\tlatencyMs\022\035\n\ncost_units\030\020 \001(\003R\tcostUnit" +
      "s\022!\n\014classes_read\030\021 \003(\tR\013classesRead\022\026\n\006" +
      "detail\030\022 \001(\tR\006detailBN\n\027com.rtdp.proto.a" +
      "gent.v1P\001Z1github.com/rtdp/rtdp/gen/go/r" +
      "tdp/agent/v1;agentv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_rtdp_agent_v1_Principal_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rtdp_agent_v1_Principal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_agent_v1_Principal_descriptor,
        new java.lang.String[] { "Kind", "Id", "TenantId", });
    internal_static_rtdp_agent_v1_DelegationLink_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rtdp_agent_v1_DelegationLink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_agent_v1_DelegationLink_descriptor,
        new java.lang.String[] { "AgentId", "AgentVersion", "AgentKind", "Scopes", "IssuedAt", "ExpiresAt", "GrantId", "MaxAutonomy", });
    internal_static_rtdp_agent_v1_DelegationChain_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rtdp_agent_v1_DelegationChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_agent_v1_DelegationChain_descriptor,
        new java.lang.String[] { "Principal", "Links", "Proof", "ProofKid", });
    internal_static_rtdp_agent_v1_AgentCall_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_rtdp_agent_v1_AgentCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_agent_v1_AgentCall_descriptor,
        new java.lang.String[] { "CallId", "At", "TenantId", "Environment", "TaskId", "Purpose", "PrincipalId", "AgentId", "AgentVersion", "ChainDepth", "Tool", "Backend", "Outcome", "DecisionId", "LatencyMs", "CostUnits", "ClassesRead", "Detail", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
