// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/agent/v1/agent.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.agent.v1;

@com.google.protobuf.Generated
public interface DelegationChainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.agent.v1.DelegationChain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rtdp.agent.v1.Principal principal = 1 [json_name = "principal"];</code>
   * @return Whether the principal field is set.
   */
  boolean hasPrincipal();
  /**
   * <code>.rtdp.agent.v1.Principal principal = 1 [json_name = "principal"];</code>
   * @return The principal.
   */
  com.rtdp.proto.agent.v1.Principal getPrincipal();
  /**
   * <code>.rtdp.agent.v1.Principal principal = 1 [json_name = "principal"];</code>
   */
  com.rtdp.proto.agent.v1.PrincipalOrBuilder getPrincipalOrBuilder();

  /**
   * <code>repeated .rtdp.agent.v1.DelegationLink links = 2 [json_name = "links"];</code>
   */
  java.util.List<com.rtdp.proto.agent.v1.DelegationLink> 
      getLinksList();
  /**
   * <code>repeated .rtdp.agent.v1.DelegationLink links = 2 [json_name = "links"];</code>
   */
  com.rtdp.proto.agent.v1.DelegationLink getLinks(int index);
  /**
   * <code>repeated .rtdp.agent.v1.DelegationLink links = 2 [json_name = "links"];</code>
   */
  int getLinksCount();
  /**
   * <code>repeated .rtdp.agent.v1.DelegationLink links = 2 [json_name = "links"];</code>
   */
  java.util.List<? extends com.rtdp.proto.agent.v1.DelegationLinkOrBuilder> 
      getLinksOrBuilderList();
  /**
   * <code>repeated .rtdp.agent.v1.DelegationLink links = 2 [json_name = "links"];</code>
   */
  com.rtdp.proto.agent.v1.DelegationLinkOrBuilder getLinksOrBuilder(
      int index);

  /**
   * <code>string proof = 3 [json_name = "proof"];</code>
   * @return The proof.
   */
  java.lang.String getProof();
  /**
   * <code>string proof = 3 [json_name = "proof"];</code>
   * @return The bytes for proof.
   */
  com.google.protobuf.ByteString
      getProofBytes();

  /**
   * <code>string proof_kid = 4 [json_name = "proofKid"];</code>
   * @return The proofKid.
   */
  java.lang.String getProofKid();
  /**
   * <code>string proof_kid = 4 [json_name = "proofKid"];</code>
   * @return The bytes for proofKid.
   */
  com.google.protobuf.ByteString
      getProofKidBytes();
}
