// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/agent/v1/agent.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.agent.v1;

@com.google.protobuf.Generated
public interface PrincipalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.agent.v1.Principal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rtdp.agent.v1.Principal.Kind kind = 1 [json_name = "kind"];</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.rtdp.agent.v1.Principal.Kind kind = 1 [json_name = "kind"];</code>
   * @return The kind.
   */
  com.rtdp.proto.agent.v1.Principal.Kind getKind();

  /**
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();
}
