// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/decision.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface ActionCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.ActionCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command_id = 1 [json_name = "commandId"];</code>
   * @return The commandId.
   */
  java.lang.String getCommandId();
  /**
   * <code>string command_id = 1 [json_name = "commandId"];</code>
   * @return The bytes for commandId.
   */
  com.google.protobuf.ByteString
      getCommandIdBytes();

  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The environment.
   */
  java.lang.String getEnvironment();
  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The bytes for environment.
   */
  com.google.protobuf.ByteString
      getEnvironmentBytes();

  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The enum numeric value on the wire for mode.
   */
  int getModeValue();
  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The mode.
   */
  com.rtdp.proto.v1.Mode getMode();

  /**
   * <code>string decision_id = 5 [json_name = "decisionId"];</code>
   * @return The decisionId.
   */
  java.lang.String getDecisionId();
  /**
   * <code>string decision_id = 5 [json_name = "decisionId"];</code>
   * @return The bytes for decisionId.
   */
  com.google.protobuf.ByteString
      getDecisionIdBytes();

  /**
   * <code>int64 decision_generation = 6 [json_name = "decisionGeneration"];</code>
   * @return The decisionGeneration.
   */
  long getDecisionGeneration();

  /**
   * <code>string action_type = 7 [json_name = "actionType"];</code>
   * @return The actionType.
   */
  java.lang.String getActionType();
  /**
   * <code>string action_type = 7 [json_name = "actionType"];</code>
   * @return The bytes for actionType.
   */
  com.google.protobuf.ByteString
      getActionTypeBytes();

  /**
   * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
   * @return The idempotencyKey.
   */
  java.lang.String getIdempotencyKey();
  /**
   * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
   * @return The bytes for idempotencyKey.
   */
  com.google.protobuf.ByteString
      getIdempotencyKeyBytes();

  /**
   * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
   * @return The adapterRef.
   */
  java.lang.String getAdapterRef();
  /**
   * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
   * @return The bytes for adapterRef.
   */
  com.google.protobuf.ByteString
      getAdapterRefBytes();

  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  int getPayloadCount();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  boolean containsPayload(
      java.lang.String key);
  /**
   * Use {@link #getPayloadMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getPayload();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getPayloadMap();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  /* nullable */
com.rtdp.proto.v1.TypedValue getPayloadOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue);
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  com.rtdp.proto.v1.TypedValue getPayloadOrThrow(
      java.lang.String key);

  /**
   * <code>int64 intent_ttl_ms = 11 [json_name = "intentTtlMs"];</code>
   * @return The intentTtlMs.
   */
  long getIntentTtlMs();

  /**
   * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
