// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/decision.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * <pre>
 * ActionCommand is the durable form consumed by the action dispatcher.
 * </pre>
 *
 * Protobuf type {@code rtdp.v1.ActionCommand}
 */
@com.google.protobuf.Generated
public final class ActionCommand extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rtdp.v1.ActionCommand)
    ActionCommandOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ActionCommand");
  }
  // Use ActionCommand.newBuilder() to construct.
  private ActionCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ActionCommand() {
    commandId_ = "";
    tenantId_ = "";
    environment_ = "";
    mode_ = 0;
    decisionId_ = "";
    actionType_ = "";
    idempotencyKey_ = "";
    adapterRef_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionCommand_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 10:
        return internalGetPayload();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rtdp.proto.v1.ActionCommand.class, com.rtdp.proto.v1.ActionCommand.Builder.class);
  }

  private int bitField0_;
  public static final int COMMAND_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commandId_ = "";
  /**
   * <code>string command_id = 1 [json_name = "commandId"];</code>
   * @return The commandId.
   */
  @java.lang.Override
  public java.lang.String getCommandId() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandId_ = s;
      return s;
    }
  }
  /**
   * <code>string command_id = 1 [json_name = "commandId"];</code>
   * @return The bytes for commandId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandIdBytes() {
    java.lang.Object ref = commandId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENVIRONMENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object environment_ = "";
  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The environment.
   */
  @java.lang.Override
  public java.lang.String getEnvironment() {
    java.lang.Object ref = environment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      environment_ = s;
      return s;
    }
  }
  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The bytes for environment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvironmentBytes() {
    java.lang.Object ref = environment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      environment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODE_FIELD_NUMBER = 4;
  private int mode_ = 0;
  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The enum numeric value on the wire for mode.
   */
  @java.lang.Override public int getModeValue() {
    return mode_;
  }
  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The mode.
   */
  @java.lang.Override public com.rtdp.proto.v1.Mode getMode() {
    com.rtdp.proto.v1.Mode result = com.rtdp.proto.v1.Mode.forNumber(mode_);
    return result == null ? com.rtdp.proto.v1.Mode.UNRECOGNIZED : result;
  }

  public static final int DECISION_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object decisionId_ = "";
  /**
   * <code>string decision_id = 5 [json_name = "decisionId"];</code>
   * @return The decisionId.
   */
  @java.lang.Override
  public java.lang.String getDecisionId() {
    java.lang.Object ref = decisionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      decisionId_ = s;
      return s;
    }
  }
  /**
   * <code>string decision_id = 5 [json_name = "decisionId"];</code>
   * @return The bytes for decisionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDecisionIdBytes() {
    java.lang.Object ref = decisionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      decisionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DECISION_GENERATION_FIELD_NUMBER = 6;
  private long decisionGeneration_ = 0L;
  /**
   * <code>int64 decision_generation = 6 [json_name = "decisionGeneration"];</code>
   * @return The decisionGeneration.
   */
  @java.lang.Override
  public long getDecisionGeneration() {
    return decisionGeneration_;
  }

  public static final int ACTION_TYPE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actionType_ = "";
  /**
   * <code>string action_type = 7 [json_name = "actionType"];</code>
   * @return The actionType.
   */
  @java.lang.Override
  public java.lang.String getActionType() {
    java.lang.Object ref = actionType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actionType_ = s;
      return s;
    }
  }
  /**
   * <code>string action_type = 7 [json_name = "actionType"];</code>
   * @return The bytes for actionType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionTypeBytes() {
    java.lang.Object ref = actionType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actionType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDEMPOTENCY_KEY_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idempotencyKey_ = "";
  /**
   * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
   * @return The idempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getIdempotencyKey() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idempotencyKey_ = s;
      return s;
    }
  }
  /**
   * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
   * @return The bytes for idempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdempotencyKeyBytes() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idempotencyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADAPTER_REF_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object adapterRef_ = "";
  /**
   * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
   * @return The adapterRef.
   */
  @java.lang.Override
  public java.lang.String getAdapterRef() {
    java.lang.Object ref = adapterRef_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      adapterRef_ = s;
      return s;
    }
  }
  /**
   * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
   * @return The bytes for adapterRef.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdapterRefBytes() {
    java.lang.Object ref = adapterRef_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      adapterRef_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 10;
  private static final class PayloadDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.rtdp.proto.v1.TypedValue>newDefaultInstance(
                com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionCommand_PayloadEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.rtdp.proto.v1.TypedValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.rtdp.proto.v1.TypedValue> payload_;
  private com.google.protobuf.MapField<java.lang.String, com.rtdp.proto.v1.TypedValue>
  internalGetPayload() {
    if (payload_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PayloadDefaultEntryHolder.defaultEntry);
    }
    return payload_;
  }
  public int getPayloadCount() {
    return internalGetPayload().getMap().size();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public boolean containsPayload(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetPayload().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPayloadMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayload() {
    return getPayloadMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayloadMap() {
    return internalGetPayload().getMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.rtdp.proto.v1.TypedValue getPayloadOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetPayload().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.TypedValue getPayloadOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetPayload().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int INTENT_TTL_MS_FIELD_NUMBER = 11;
  private long intentTtlMs_ = 0L;
  /**
   * <code>int64 intent_ttl_ms = 11 [json_name = "intentTtlMs"];</code>
   * @return The intentTtlMs.
   */
  @java.lang.Override
  public long getIntentTtlMs() {
    return intentTtlMs_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 12;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(commandId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, commandId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(environment_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, environment_);
    }
    if (mode_ != com.rtdp.proto.v1.Mode.MODE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, mode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(decisionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, decisionId_);
    }
    if (decisionGeneration_ != 0L) {
      output.writeInt64(6, decisionGeneration_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, actionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, idempotencyKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(adapterRef_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, adapterRef_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetPayload(),
        PayloadDefaultEntryHolder.defaultEntry,
        10);
    if (intentTtlMs_ != 0L) {
      output.writeInt64(11, intentTtlMs_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(12, getCreatedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(commandId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, commandId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(environment_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, environment_);
    }
    if (mode_ != com.rtdp.proto.v1.Mode.MODE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, mode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(decisionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, decisionId_);
    }
    if (decisionGeneration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, decisionGeneration_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, actionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, idempotencyKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(adapterRef_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, adapterRef_);
    }
    for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> entry
         : internalGetPayload().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
      payload__ = PayloadDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, payload__);
    }
    if (intentTtlMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, intentTtlMs_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getCreatedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rtdp.proto.v1.ActionCommand)) {
      return super.equals(obj);
    }
    com.rtdp.proto.v1.ActionCommand other = (com.rtdp.proto.v1.ActionCommand) obj;

    if (!getCommandId()
        .equals(other.getCommandId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getEnvironment()
        .equals(other.getEnvironment())) return false;
    if (mode_ != other.mode_) return false;
    if (!getDecisionId()
        .equals(other.getDecisionId())) return false;
    if (getDecisionGeneration()
        != other.getDecisionGeneration()) return false;
    if (!getActionType()
        .equals(other.getActionType())) return false;
    if (!getIdempotencyKey()
        .equals(other.getIdempotencyKey())) return false;
    if (!getAdapterRef()
        .equals(other.getAdapterRef())) return false;
    if (!internalGetPayload().equals(
        other.internalGetPayload())) return false;
    if (getIntentTtlMs()
        != other.getIntentTtlMs()) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCommandId().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + ENVIRONMENT_FIELD_NUMBER;
    hash = (53 * hash) + getEnvironment().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + mode_;
    hash = (37 * hash) + DECISION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDecisionId().hashCode();
    hash = (37 * hash) + DECISION_GENERATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDecisionGeneration());
    hash = (37 * hash) + ACTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getActionType().hashCode();
    hash = (37 * hash) + IDEMPOTENCY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getIdempotencyKey().hashCode();
    hash = (37 * hash) + ADAPTER_REF_FIELD_NUMBER;
    hash = (53 * hash) + getAdapterRef().hashCode();
    if (!internalGetPayload().getMap().isEmpty()) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPayload().hashCode();
    }
    hash = (37 * hash) + INTENT_TTL_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIntentTtlMs());
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rtdp.proto.v1.ActionCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rtdp.proto.v1.ActionCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ActionCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rtdp.proto.v1.ActionCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ActionCommand is the durable form consumed by the action dispatcher.
   * </pre>
   *
   * Protobuf type {@code rtdp.v1.ActionCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rtdp.v1.ActionCommand)
      com.rtdp.proto.v1.ActionCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionCommand_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 10:
          return internalGetPayload();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 10:
          return internalGetMutablePayload();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rtdp.proto.v1.ActionCommand.class, com.rtdp.proto.v1.ActionCommand.Builder.class);
    }

    // Construct using com.rtdp.proto.v1.ActionCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCreatedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commandId_ = "";
      tenantId_ = "";
      environment_ = "";
      mode_ = 0;
      decisionId_ = "";
      decisionGeneration_ = 0L;
      actionType_ = "";
      idempotencyKey_ = "";
      adapterRef_ = "";
      internalGetMutablePayload().clear();
      intentTtlMs_ = 0L;
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionCommand_descriptor;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ActionCommand getDefaultInstanceForType() {
      return com.rtdp.proto.v1.ActionCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ActionCommand build() {
      com.rtdp.proto.v1.ActionCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ActionCommand buildPartial() {
      com.rtdp.proto.v1.ActionCommand result = new com.rtdp.proto.v1.ActionCommand(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rtdp.proto.v1.ActionCommand result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commandId_ = commandId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.environment_ = environment_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mode_ = mode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.decisionId_ = decisionId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.decisionGeneration_ = decisionGeneration_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.actionType_ = actionType_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.idempotencyKey_ = idempotencyKey_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.adapterRef_ = adapterRef_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.payload_ = internalGetPayload().build(PayloadDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.intentTtlMs_ = intentTtlMs_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rtdp.proto.v1.ActionCommand) {
        return mergeFrom((com.rtdp.proto.v1.ActionCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rtdp.proto.v1.ActionCommand other) {
      if (other == com.rtdp.proto.v1.ActionCommand.getDefaultInstance()) return this;
      if (!other.getCommandId().isEmpty()) {
        commandId_ = other.commandId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEnvironment().isEmpty()) {
        environment_ = other.environment_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.mode_ != 0) {
        setModeValue(other.getModeValue());
      }
      if (!other.getDecisionId().isEmpty()) {
        decisionId_ = other.decisionId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getDecisionGeneration() != 0L) {
        setDecisionGeneration(other.getDecisionGeneration());
      }
      if (!other.getActionType().isEmpty()) {
        actionType_ = other.actionType_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getIdempotencyKey().isEmpty()) {
        idempotencyKey_ = other.idempotencyKey_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getAdapterRef().isEmpty()) {
        adapterRef_ = other.adapterRef_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      internalGetMutablePayload().mergeFrom(
          other.internalGetPayload());
      bitField0_ |= 0x00000200;
      if (other.getIntentTtlMs() != 0L) {
        setIntentTtlMs(other.getIntentTtlMs());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              commandId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              environment_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              mode_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              decisionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              decisionGeneration_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              actionType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              idempotencyKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              adapterRef_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
              payload__ = input.readMessage(
                  PayloadDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePayload().ensureBuilderMap().put(
                  payload__.getKey(), payload__.getValue());
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              intentTtlMs_ = input.readInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              input.readMessage(
                  internalGetCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object commandId_ = "";
    /**
     * <code>string command_id = 1 [json_name = "commandId"];</code>
     * @return The commandId.
     */
    public java.lang.String getCommandId() {
      java.lang.Object ref = commandId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string command_id = 1 [json_name = "commandId"];</code>
     * @return The bytes for commandId.
     */
    public com.google.protobuf.ByteString
        getCommandIdBytes() {
      java.lang.Object ref = commandId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string command_id = 1 [json_name = "commandId"];</code>
     * @param value The commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string command_id = 1 [json_name = "commandId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandId() {
      commandId_ = getDefaultInstance().getCommandId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string command_id = 1 [json_name = "commandId"];</code>
     * @param value The bytes for commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object environment_ = "";
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @return The environment.
     */
    public java.lang.String getEnvironment() {
      java.lang.Object ref = environment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        environment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @return The bytes for environment.
     */
    public com.google.protobuf.ByteString
        getEnvironmentBytes() {
      java.lang.Object ref = environment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        environment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @param value The environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironment(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      environment_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironment() {
      environment_ = getDefaultInstance().getEnvironment();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @param value The bytes for environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      environment_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int mode_ = 0;
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @return The enum numeric value on the wire for mode.
     */
    @java.lang.Override public int getModeValue() {
      return mode_;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @param value The enum numeric value on the wire for mode to set.
     * @return This builder for chaining.
     */
    public Builder setModeValue(int value) {
      mode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @return The mode.
     */
    @java.lang.Override
    public com.rtdp.proto.v1.Mode getMode() {
      com.rtdp.proto.v1.Mode result = com.rtdp.proto.v1.Mode.forNumber(mode_);
      return result == null ? com.rtdp.proto.v1.Mode.UNRECOGNIZED : result;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(com.rtdp.proto.v1.Mode value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      mode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      mode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object decisionId_ = "";
    /**
     * <code>string decision_id = 5 [json_name = "decisionId"];</code>
     * @return The decisionId.
     */
    public java.lang.String getDecisionId() {
      java.lang.Object ref = decisionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        decisionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string decision_id = 5 [json_name = "decisionId"];</code>
     * @return The bytes for decisionId.
     */
    public com.google.protobuf.ByteString
        getDecisionIdBytes() {
      java.lang.Object ref = decisionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        decisionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string decision_id = 5 [json_name = "decisionId"];</code>
     * @param value The decisionId to set.
     * @return This builder for chaining.
     */
    public Builder setDecisionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      decisionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string decision_id = 5 [json_name = "decisionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDecisionId() {
      decisionId_ = getDefaultInstance().getDecisionId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string decision_id = 5 [json_name = "decisionId"];</code>
     * @param value The bytes for decisionId to set.
     * @return This builder for chaining.
     */
    public Builder setDecisionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      decisionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long decisionGeneration_ ;
    /**
     * <code>int64 decision_generation = 6 [json_name = "decisionGeneration"];</code>
     * @return The decisionGeneration.
     */
    @java.lang.Override
    public long getDecisionGeneration() {
      return decisionGeneration_;
    }
    /**
     * <code>int64 decision_generation = 6 [json_name = "decisionGeneration"];</code>
     * @param value The decisionGeneration to set.
     * @return This builder for chaining.
     */
    public Builder setDecisionGeneration(long value) {

      decisionGeneration_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 decision_generation = 6 [json_name = "decisionGeneration"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDecisionGeneration() {
      bitField0_ = (bitField0_ & ~0x00000020);
      decisionGeneration_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object actionType_ = "";
    /**
     * <code>string action_type = 7 [json_name = "actionType"];</code>
     * @return The actionType.
     */
    public java.lang.String getActionType() {
      java.lang.Object ref = actionType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action_type = 7 [json_name = "actionType"];</code>
     * @return The bytes for actionType.
     */
    public com.google.protobuf.ByteString
        getActionTypeBytes() {
      java.lang.Object ref = actionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action_type = 7 [json_name = "actionType"];</code>
     * @param value The actionType to set.
     * @return This builder for chaining.
     */
    public Builder setActionType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actionType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string action_type = 7 [json_name = "actionType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActionType() {
      actionType_ = getDefaultInstance().getActionType();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string action_type = 7 [json_name = "actionType"];</code>
     * @param value The bytes for actionType to set.
     * @return This builder for chaining.
     */
    public Builder setActionTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actionType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object idempotencyKey_ = "";
    /**
     * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     * @return The idempotencyKey.
     */
    public java.lang.String getIdempotencyKey() {
      java.lang.Object ref = idempotencyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idempotencyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     * @return The bytes for idempotencyKey.
     */
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     * @param value The idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idempotencyKey_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotencyKey() {
      idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 8 [json_name = "idempotencyKey"];</code>
     * @param value The bytes for idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idempotencyKey_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object adapterRef_ = "";
    /**
     * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
     * @return The adapterRef.
     */
    public java.lang.String getAdapterRef() {
      java.lang.Object ref = adapterRef_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adapterRef_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
     * @return The bytes for adapterRef.
     */
    public com.google.protobuf.ByteString
        getAdapterRefBytes() {
      java.lang.Object ref = adapterRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adapterRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
     * @param value The adapterRef to set.
     * @return This builder for chaining.
     */
    public Builder setAdapterRef(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      adapterRef_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAdapterRef() {
      adapterRef_ = getDefaultInstance().getAdapterRef();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string adapter_ref = 9 [json_name = "adapterRef"];</code>
     * @param value The bytes for adapterRef to set.
     * @return This builder for chaining.
     */
    public Builder setAdapterRefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      adapterRef_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private static final class PayloadConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue> {
      @java.lang.Override
      public com.rtdp.proto.v1.TypedValue build(com.rtdp.proto.v1.TypedValueOrBuilder val) {
        if (val instanceof com.rtdp.proto.v1.TypedValue) { return (com.rtdp.proto.v1.TypedValue) val; }
        return ((com.rtdp.proto.v1.TypedValue.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry() {
        return PayloadDefaultEntryHolder.defaultEntry;
      }
    };
    private static final PayloadConverter payloadConverter = new PayloadConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder> payload_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetPayload() {
      if (payload_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(payloadConverter);
      }
      return payload_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetMutablePayload() {
      if (payload_ == null) {
        payload_ = new com.google.protobuf.MapFieldBuilder<>(payloadConverter);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return payload_;
    }
    public int getPayloadCount() {
      return internalGetPayload().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public boolean containsPayload(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPayload().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getPayloadMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayload() {
      return getPayloadMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayloadMap() {
      return internalGetPayload().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.rtdp.proto.v1.TypedValue getPayloadOrDefault(
        java.lang.String key,
        /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutablePayload().ensureBuilderMap();
      return map.containsKey(key) ? payloadConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public com.rtdp.proto.v1.TypedValue getPayloadOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutablePayload().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return payloadConverter.build(map.get(key));
    }
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000200);
      internalGetMutablePayload().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    public Builder removePayload(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutablePayload().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
        getMutablePayload() {
      bitField0_ |= 0x00000200;
      return internalGetMutablePayload().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    public Builder putPayload(
        java.lang.String key,
        com.rtdp.proto.v1.TypedValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutablePayload().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    public Builder putAllPayload(
        java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> values) {
      for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutablePayload().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 10 [json_name = "payload"];</code>
     */
    public com.rtdp.proto.v1.TypedValue.Builder putPayloadBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> builderMap = internalGetMutablePayload().ensureBuilderMap();
      com.rtdp.proto.v1.TypedValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.rtdp.proto.v1.TypedValue.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.rtdp.proto.v1.TypedValue) {
        entry = ((com.rtdp.proto.v1.TypedValue) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.rtdp.proto.v1.TypedValue.Builder) entry;
    }

    private long intentTtlMs_ ;
    /**
     * <code>int64 intent_ttl_ms = 11 [json_name = "intentTtlMs"];</code>
     * @return The intentTtlMs.
     */
    @java.lang.Override
    public long getIntentTtlMs() {
      return intentTtlMs_;
    }
    /**
     * <code>int64 intent_ttl_ms = 11 [json_name = "intentTtlMs"];</code>
     * @param value The intentTtlMs to set.
     * @return This builder for chaining.
     */
    public Builder setIntentTtlMs(long value) {

      intentTtlMs_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int64 intent_ttl_ms = 11 [json_name = "intentTtlMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIntentTtlMs() {
      bitField0_ = (bitField0_ & ~0x00000400);
      intentTtlMs_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000800);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return internalGetCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 12 [json_name = "createdAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:rtdp.v1.ActionCommand)
  }

  // @@protoc_insertion_point(class_scope:rtdp.v1.ActionCommand)
  private static final com.rtdp.proto.v1.ActionCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rtdp.proto.v1.ActionCommand();
  }

  public static com.rtdp.proto.v1.ActionCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionCommand>
      PARSER = new com.google.protobuf.AbstractParser<ActionCommand>() {
    @java.lang.Override
    public ActionCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ActionCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rtdp.proto.v1.ActionCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

