// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/decision.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface ActionIntentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.ActionIntent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string action_type = 1 [json_name = "actionType"];</code>
   * @return The actionType.
   */
  java.lang.String getActionType();
  /**
   * <code>string action_type = 1 [json_name = "actionType"];</code>
   * @return The bytes for actionType.
   */
  com.google.protobuf.ByteString
      getActionTypeBytes();

  /**
   * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
   * @return The idempotencyKey.
   */
  java.lang.String getIdempotencyKey();
  /**
   * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
   * @return The bytes for idempotencyKey.
   */
  com.google.protobuf.ByteString
      getIdempotencyKeyBytes();

  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  int getPayloadCount();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  boolean containsPayload(
      java.lang.String key);
  /**
   * Use {@link #getPayloadMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getPayload();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getPayloadMap();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  /* nullable */
com.rtdp.proto.v1.TypedValue getPayloadOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue);
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  com.rtdp.proto.v1.TypedValue getPayloadOrThrow(
      java.lang.String key);

  /**
   * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
   * @return The adapterRef.
   */
  java.lang.String getAdapterRef();
  /**
   * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
   * @return The bytes for adapterRef.
   */
  com.google.protobuf.ByteString
      getAdapterRefBytes();

  /**
   * <code>int64 ttl_ms = 5 [json_name = "ttlMs"];</code>
   * @return The ttlMs.
   */
  long getTtlMs();
}
