// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/decision.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * <pre>
 * ActionIntent is a permitted desired effect — not yet an executed action.
 * </pre>
 *
 * Protobuf type {@code rtdp.v1.ActionIntent}
 */
@com.google.protobuf.Generated
public final class ActionIntent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rtdp.v1.ActionIntent)
    ActionIntentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ActionIntent");
  }
  // Use ActionIntent.newBuilder() to construct.
  private ActionIntent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ActionIntent() {
    actionType_ = "";
    idempotencyKey_ = "";
    adapterRef_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionIntent_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetPayload();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionIntent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rtdp.proto.v1.ActionIntent.class, com.rtdp.proto.v1.ActionIntent.Builder.class);
  }

  public static final int ACTION_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actionType_ = "";
  /**
   * <code>string action_type = 1 [json_name = "actionType"];</code>
   * @return The actionType.
   */
  @java.lang.Override
  public java.lang.String getActionType() {
    java.lang.Object ref = actionType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actionType_ = s;
      return s;
    }
  }
  /**
   * <code>string action_type = 1 [json_name = "actionType"];</code>
   * @return The bytes for actionType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionTypeBytes() {
    java.lang.Object ref = actionType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actionType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDEMPOTENCY_KEY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idempotencyKey_ = "";
  /**
   * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
   * @return The idempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getIdempotencyKey() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idempotencyKey_ = s;
      return s;
    }
  }
  /**
   * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
   * @return The bytes for idempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdempotencyKeyBytes() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idempotencyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 3;
  private static final class PayloadDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.rtdp.proto.v1.TypedValue>newDefaultInstance(
                com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionIntent_PayloadEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.rtdp.proto.v1.TypedValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.rtdp.proto.v1.TypedValue> payload_;
  private com.google.protobuf.MapField<java.lang.String, com.rtdp.proto.v1.TypedValue>
  internalGetPayload() {
    if (payload_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PayloadDefaultEntryHolder.defaultEntry);
    }
    return payload_;
  }
  public int getPayloadCount() {
    return internalGetPayload().getMap().size();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public boolean containsPayload(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetPayload().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPayloadMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayload() {
    return getPayloadMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayloadMap() {
    return internalGetPayload().getMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.rtdp.proto.v1.TypedValue getPayloadOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetPayload().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.TypedValue getPayloadOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetPayload().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ADAPTER_REF_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object adapterRef_ = "";
  /**
   * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
   * @return The adapterRef.
   */
  @java.lang.Override
  public java.lang.String getAdapterRef() {
    java.lang.Object ref = adapterRef_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      adapterRef_ = s;
      return s;
    }
  }
  /**
   * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
   * @return The bytes for adapterRef.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdapterRefBytes() {
    java.lang.Object ref = adapterRef_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      adapterRef_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TTL_MS_FIELD_NUMBER = 5;
  private long ttlMs_ = 0L;
  /**
   * <code>int64 ttl_ms = 5 [json_name = "ttlMs"];</code>
   * @return The ttlMs.
   */
  @java.lang.Override
  public long getTtlMs() {
    return ttlMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, actionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, idempotencyKey_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetPayload(),
        PayloadDefaultEntryHolder.defaultEntry,
        3);
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(adapterRef_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, adapterRef_);
    }
    if (ttlMs_ != 0L) {
      output.writeInt64(5, ttlMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, actionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, idempotencyKey_);
    }
    for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> entry
         : internalGetPayload().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
      payload__ = PayloadDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, payload__);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(adapterRef_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, adapterRef_);
    }
    if (ttlMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, ttlMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rtdp.proto.v1.ActionIntent)) {
      return super.equals(obj);
    }
    com.rtdp.proto.v1.ActionIntent other = (com.rtdp.proto.v1.ActionIntent) obj;

    if (!getActionType()
        .equals(other.getActionType())) return false;
    if (!getIdempotencyKey()
        .equals(other.getIdempotencyKey())) return false;
    if (!internalGetPayload().equals(
        other.internalGetPayload())) return false;
    if (!getAdapterRef()
        .equals(other.getAdapterRef())) return false;
    if (getTtlMs()
        != other.getTtlMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getActionType().hashCode();
    hash = (37 * hash) + IDEMPOTENCY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getIdempotencyKey().hashCode();
    if (!internalGetPayload().getMap().isEmpty()) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPayload().hashCode();
    }
    hash = (37 * hash) + ADAPTER_REF_FIELD_NUMBER;
    hash = (53 * hash) + getAdapterRef().hashCode();
    hash = (37 * hash) + TTL_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTtlMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rtdp.proto.v1.ActionIntent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rtdp.proto.v1.ActionIntent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ActionIntent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rtdp.proto.v1.ActionIntent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ActionIntent is a permitted desired effect — not yet an executed action.
   * </pre>
   *
   * Protobuf type {@code rtdp.v1.ActionIntent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rtdp.v1.ActionIntent)
      com.rtdp.proto.v1.ActionIntentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionIntent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetPayload();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutablePayload();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionIntent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rtdp.proto.v1.ActionIntent.class, com.rtdp.proto.v1.ActionIntent.Builder.class);
    }

    // Construct using com.rtdp.proto.v1.ActionIntent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actionType_ = "";
      idempotencyKey_ = "";
      internalGetMutablePayload().clear();
      adapterRef_ = "";
      ttlMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_ActionIntent_descriptor;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ActionIntent getDefaultInstanceForType() {
      return com.rtdp.proto.v1.ActionIntent.getDefaultInstance();
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ActionIntent build() {
      com.rtdp.proto.v1.ActionIntent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ActionIntent buildPartial() {
      com.rtdp.proto.v1.ActionIntent result = new com.rtdp.proto.v1.ActionIntent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rtdp.proto.v1.ActionIntent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.actionType_ = actionType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idempotencyKey_ = idempotencyKey_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.payload_ = internalGetPayload().build(PayloadDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.adapterRef_ = adapterRef_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ttlMs_ = ttlMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rtdp.proto.v1.ActionIntent) {
        return mergeFrom((com.rtdp.proto.v1.ActionIntent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rtdp.proto.v1.ActionIntent other) {
      if (other == com.rtdp.proto.v1.ActionIntent.getDefaultInstance()) return this;
      if (!other.getActionType().isEmpty()) {
        actionType_ = other.actionType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getIdempotencyKey().isEmpty()) {
        idempotencyKey_ = other.idempotencyKey_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      internalGetMutablePayload().mergeFrom(
          other.internalGetPayload());
      bitField0_ |= 0x00000004;
      if (!other.getAdapterRef().isEmpty()) {
        adapterRef_ = other.adapterRef_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getTtlMs() != 0L) {
        setTtlMs(other.getTtlMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              actionType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              idempotencyKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
              payload__ = input.readMessage(
                  PayloadDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePayload().ensureBuilderMap().put(
                  payload__.getKey(), payload__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              adapterRef_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              ttlMs_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object actionType_ = "";
    /**
     * <code>string action_type = 1 [json_name = "actionType"];</code>
     * @return The actionType.
     */
    public java.lang.String getActionType() {
      java.lang.Object ref = actionType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action_type = 1 [json_name = "actionType"];</code>
     * @return The bytes for actionType.
     */
    public com.google.protobuf.ByteString
        getActionTypeBytes() {
      java.lang.Object ref = actionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action_type = 1 [json_name = "actionType"];</code>
     * @param value The actionType to set.
     * @return This builder for chaining.
     */
    public Builder setActionType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actionType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string action_type = 1 [json_name = "actionType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActionType() {
      actionType_ = getDefaultInstance().getActionType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string action_type = 1 [json_name = "actionType"];</code>
     * @param value The bytes for actionType to set.
     * @return This builder for chaining.
     */
    public Builder setActionTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actionType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object idempotencyKey_ = "";
    /**
     * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
     * @return The idempotencyKey.
     */
    public java.lang.String getIdempotencyKey() {
      java.lang.Object ref = idempotencyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idempotencyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
     * @return The bytes for idempotencyKey.
     */
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
     * @param value The idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idempotencyKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotencyKey() {
      idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 2 [json_name = "idempotencyKey"];</code>
     * @param value The bytes for idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idempotencyKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private static final class PayloadConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue> {
      @java.lang.Override
      public com.rtdp.proto.v1.TypedValue build(com.rtdp.proto.v1.TypedValueOrBuilder val) {
        if (val instanceof com.rtdp.proto.v1.TypedValue) { return (com.rtdp.proto.v1.TypedValue) val; }
        return ((com.rtdp.proto.v1.TypedValue.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry() {
        return PayloadDefaultEntryHolder.defaultEntry;
      }
    };
    private static final PayloadConverter payloadConverter = new PayloadConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder> payload_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetPayload() {
      if (payload_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(payloadConverter);
      }
      return payload_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetMutablePayload() {
      if (payload_ == null) {
        payload_ = new com.google.protobuf.MapFieldBuilder<>(payloadConverter);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return payload_;
    }
    public int getPayloadCount() {
      return internalGetPayload().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public boolean containsPayload(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPayload().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getPayloadMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayload() {
      return getPayloadMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getPayloadMap() {
      return internalGetPayload().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.rtdp.proto.v1.TypedValue getPayloadOrDefault(
        java.lang.String key,
        /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutablePayload().ensureBuilderMap();
      return map.containsKey(key) ? payloadConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    @java.lang.Override
    public com.rtdp.proto.v1.TypedValue getPayloadOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutablePayload().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return payloadConverter.build(map.get(key));
    }
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutablePayload().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    public Builder removePayload(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutablePayload().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
        getMutablePayload() {
      bitField0_ |= 0x00000004;
      return internalGetMutablePayload().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    public Builder putPayload(
        java.lang.String key,
        com.rtdp.proto.v1.TypedValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutablePayload().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    public Builder putAllPayload(
        java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> values) {
      for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutablePayload().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; payload = 3 [json_name = "payload"];</code>
     */
    public com.rtdp.proto.v1.TypedValue.Builder putPayloadBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> builderMap = internalGetMutablePayload().ensureBuilderMap();
      com.rtdp.proto.v1.TypedValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.rtdp.proto.v1.TypedValue.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.rtdp.proto.v1.TypedValue) {
        entry = ((com.rtdp.proto.v1.TypedValue) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.rtdp.proto.v1.TypedValue.Builder) entry;
    }

    private java.lang.Object adapterRef_ = "";
    /**
     * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
     * @return The adapterRef.
     */
    public java.lang.String getAdapterRef() {
      java.lang.Object ref = adapterRef_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adapterRef_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
     * @return The bytes for adapterRef.
     */
    public com.google.protobuf.ByteString
        getAdapterRefBytes() {
      java.lang.Object ref = adapterRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adapterRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
     * @param value The adapterRef to set.
     * @return This builder for chaining.
     */
    public Builder setAdapterRef(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      adapterRef_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAdapterRef() {
      adapterRef_ = getDefaultInstance().getAdapterRef();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string adapter_ref = 4 [json_name = "adapterRef"];</code>
     * @param value The bytes for adapterRef to set.
     * @return This builder for chaining.
     */
    public Builder setAdapterRefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      adapterRef_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long ttlMs_ ;
    /**
     * <code>int64 ttl_ms = 5 [json_name = "ttlMs"];</code>
     * @return The ttlMs.
     */
    @java.lang.Override
    public long getTtlMs() {
      return ttlMs_;
    }
    /**
     * <code>int64 ttl_ms = 5 [json_name = "ttlMs"];</code>
     * @param value The ttlMs to set.
     * @return This builder for chaining.
     */
    public Builder setTtlMs(long value) {

      ttlMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ttl_ms = 5 [json_name = "ttlMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTtlMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      ttlMs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rtdp.v1.ActionIntent)
  }

  // @@protoc_insertion_point(class_scope:rtdp.v1.ActionIntent)
  private static final com.rtdp.proto.v1.ActionIntent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rtdp.proto.v1.ActionIntent();
  }

  public static com.rtdp.proto.v1.ActionIntent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionIntent>
      PARSER = new com.google.protobuf.AbstractParser<ActionIntent>() {
    @java.lang.Override
    public ActionIntent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ActionIntent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionIntent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rtdp.proto.v1.ActionIntent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

