// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/decision.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface AuthenticatedTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.AuthenticatedTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1 [json_name = "requestId"];</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * bound at ingress from authenticated identity
   * </pre>
   *
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * bound at ingress from authenticated identity
   * </pre>
   *
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The environment.
   */
  java.lang.String getEnvironment();
  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The bytes for environment.
   */
  com.google.protobuf.ByteString
      getEnvironmentBytes();

  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The enum numeric value on the wire for mode.
   */
  int getModeValue();
  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The mode.
   */
  com.rtdp.proto.v1.Mode getMode();

  /**
   * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>int64 transaction_revision = 6 [json_name = "transactionRevision"];</code>
   * @return The transactionRevision.
   */
  long getTransactionRevision();

  /**
   * <pre>
   * e.g. CLAIM_SUBMISSION
   * </pre>
   *
   * <code>string event_type = 7 [json_name = "eventType"];</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <pre>
   * e.g. CLAIM_SUBMISSION
   * </pre>
   *
   * <code>string event_type = 7 [json_name = "eventType"];</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <pre>
   * e.g. AGENT_PORTAL
   * </pre>
   *
   * <code>string channel = 8 [json_name = "channel"];</code>
   * @return The channel.
   */
  java.lang.String getChannel();
  /**
   * <pre>
   * e.g. AGENT_PORTAL
   * </pre>
   *
   * <code>string channel = 8 [json_name = "channel"];</code>
   * @return The bytes for channel.
   */
  com.google.protobuf.ByteString
      getChannelBytes();

  /**
   * <code>string region = 9 [json_name = "region"];</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 9 [json_name = "region"];</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <pre>
   * insured / claimant, tokenized at ingress
   * </pre>
   *
   * <code>string tokenized_claimant = 10 [json_name = "tokenizedClaimant"];</code>
   * @return The tokenizedClaimant.
   */
  java.lang.String getTokenizedClaimant();
  /**
   * <pre>
   * insured / claimant, tokenized at ingress
   * </pre>
   *
   * <code>string tokenized_claimant = 10 [json_name = "tokenizedClaimant"];</code>
   * @return The bytes for tokenizedClaimant.
   */
  com.google.protobuf.ByteString
      getTokenizedClaimantBytes();

  /**
   * <pre>
   * service provider (repair shop, clinic, ...)
   * </pre>
   *
   * <code>string provider_id = 11 [json_name = "providerId"];</code>
   * @return The providerId.
   */
  java.lang.String getProviderId();
  /**
   * <pre>
   * service provider (repair shop, clinic, ...)
   * </pre>
   *
   * <code>string provider_id = 11 [json_name = "providerId"];</code>
   * @return The bytes for providerId.
   */
  com.google.protobuf.ByteString
      getProviderIdBytes();

  /**
   * <code>string currency = 12 [json_name = "currency"];</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 12 [json_name = "currency"];</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>double amount = 13 [json_name = "amount"];</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>.google.protobuf.Timestamp event_time = 14 [json_name = "eventTime"];</code>
   * @return Whether the eventTime field is set.
   */
  boolean hasEventTime();
  /**
   * <code>.google.protobuf.Timestamp event_time = 14 [json_name = "eventTime"];</code>
   * @return The eventTime.
   */
  com.google.protobuf.Timestamp getEventTime();
  /**
   * <code>.google.protobuf.Timestamp event_time = 14 [json_name = "eventTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder();

  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; attributes = 15 [json_name = "attributes"];</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; attributes = 15 [json_name = "attributes"];</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getAttributes();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; attributes = 15 [json_name = "attributes"];</code>
   */
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getAttributesMap();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; attributes = 15 [json_name = "attributes"];</code>
   */
  /* nullable */
com.rtdp.proto.v1.TypedValue getAttributesOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue);
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; attributes = 15 [json_name = "attributes"];</code>
   */
  com.rtdp.proto.v1.TypedValue getAttributesOrThrow(
      java.lang.String key);

  /**
   * <code>string traceparent = 16 [json_name = "traceparent"];</code>
   * @return The traceparent.
   */
  java.lang.String getTraceparent();
  /**
   * <code>string traceparent = 16 [json_name = "traceparent"];</code>
   * @return The bytes for traceparent.
   */
  com.google.protobuf.ByteString
      getTraceparentBytes();
}
