// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/envelope.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * <pre>
 * Decision outcomes returned to callers.
 * </pre>
 *
 * Protobuf enum {@code rtdp.v1.Decision}
 */
@com.google.protobuf.Generated
public enum Decision
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DECISION_UNSPECIFIED = 0;</code>
   */
  DECISION_UNSPECIFIED(0),
  /**
   * <code>DECISION_APPROVE = 1;</code>
   */
  DECISION_APPROVE(1),
  /**
   * <code>DECISION_DECLINE = 2;</code>
   */
  DECISION_DECLINE(2),
  /**
   * <code>DECISION_REVIEW = 3;</code>
   */
  DECISION_REVIEW(3),
  /**
   * <code>DECISION_NOT_APPLICABLE = 4;</code>
   */
  DECISION_NOT_APPLICABLE(4),
  /**
   * <pre>
   * ADR-013: delegation chain failed authorisation (revoked grant,
   * insufficient scope). Edge rejections that never reach the
   * orchestrator still surface this outcome to the caller.
   * </pre>
   *
   * <code>DECISION_DECLINE_UNAUTHORIZED = 5;</code>
   */
  DECISION_DECLINE_UNAUTHORIZED(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Decision");
  }
  /**
   * <code>DECISION_UNSPECIFIED = 0;</code>
   */
  public static final int DECISION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DECISION_APPROVE = 1;</code>
   */
  public static final int DECISION_APPROVE_VALUE = 1;
  /**
   * <code>DECISION_DECLINE = 2;</code>
   */
  public static final int DECISION_DECLINE_VALUE = 2;
  /**
   * <code>DECISION_REVIEW = 3;</code>
   */
  public static final int DECISION_REVIEW_VALUE = 3;
  /**
   * <code>DECISION_NOT_APPLICABLE = 4;</code>
   */
  public static final int DECISION_NOT_APPLICABLE_VALUE = 4;
  /**
   * <pre>
   * ADR-013: delegation chain failed authorisation (revoked grant,
   * insufficient scope). Edge rejections that never reach the
   * orchestrator still surface this outcome to the caller.
   * </pre>
   *
   * <code>DECISION_DECLINE_UNAUTHORIZED = 5;</code>
   */
  public static final int DECISION_DECLINE_UNAUTHORIZED_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Decision valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Decision forNumber(int value) {
    switch (value) {
      case 0: return DECISION_UNSPECIFIED;
      case 1: return DECISION_APPROVE;
      case 2: return DECISION_DECLINE;
      case 3: return DECISION_REVIEW;
      case 4: return DECISION_NOT_APPLICABLE;
      case 5: return DECISION_DECLINE_UNAUTHORIZED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Decision>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Decision> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Decision>() {
          public Decision findValueByNumber(int number) {
            return Decision.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.rtdp.proto.v1.Envelope.getDescriptor().getEnumTypes().get(1);
  }

  private static final Decision[] VALUES = values();

  public static Decision valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Decision(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:rtdp.v1.Decision)
}

