// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/envelope.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface DoubleListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.DoubleList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double values = 1 [json_name = "values"];</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Double> getValuesList();
  /**
   * <code>repeated double values = 1 [json_name = "values"];</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated double values = 1 [json_name = "values"];</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  double getValues(int index);
}
