// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/services.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * Protobuf type {@code rtdp.v1.EvaluateRulesRequest}
 */
@com.google.protobuf.Generated
public final class EvaluateRulesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rtdp.v1.EvaluateRulesRequest)
    EvaluateRulesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "EvaluateRulesRequest");
  }
  // Use EvaluateRulesRequest.newBuilder() to construct.
  private EvaluateRulesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EvaluateRulesRequest() {
    rulesetDigest_ = "";
    rulesetSpecJson_ = com.google.protobuf.ByteString.EMPTY;
    presentSignalAliases_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetFeatures();
      case 4:
        return internalGetSignals();
      case 6:
        return internalGetCfg();
      case 7:
        return internalGetInput();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rtdp.proto.v1.EvaluateRulesRequest.class, com.rtdp.proto.v1.EvaluateRulesRequest.Builder.class);
  }

  public static final int RULESET_DIGEST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rulesetDigest_ = "";
  /**
   * <code>string ruleset_digest = 1 [json_name = "rulesetDigest"];</code>
   * @return The rulesetDigest.
   */
  @java.lang.Override
  public java.lang.String getRulesetDigest() {
    java.lang.Object ref = rulesetDigest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rulesetDigest_ = s;
      return s;
    }
  }
  /**
   * <code>string ruleset_digest = 1 [json_name = "rulesetDigest"];</code>
   * @return The bytes for rulesetDigest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRulesetDigestBytes() {
    java.lang.Object ref = rulesetDigest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rulesetDigest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RULESET_SPEC_JSON_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString rulesetSpecJson_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * must sha256-match ruleset_digest
   * </pre>
   *
   * <code>bytes ruleset_spec_json = 2 [json_name = "rulesetSpecJson"];</code>
   * @return The rulesetSpecJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRulesetSpecJson() {
    return rulesetSpecJson_;
  }

  public static final int FEATURES_FIELD_NUMBER = 3;
  private static final class FeaturesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.rtdp.proto.v1.TypedValue>newDefaultInstance(
                com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_FeaturesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.rtdp.proto.v1.TypedValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.rtdp.proto.v1.TypedValue> features_;
  private com.google.protobuf.MapField<java.lang.String, com.rtdp.proto.v1.TypedValue>
  internalGetFeatures() {
    if (features_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FeaturesDefaultEntryHolder.defaultEntry);
    }
    return features_;
  }
  public int getFeaturesCount() {
    return internalGetFeatures().getMap().size();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
   */
  @java.lang.Override
  public boolean containsFeatures(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFeatures().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFeaturesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getFeatures() {
    return getFeaturesMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getFeaturesMap() {
    return internalGetFeatures().getMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.rtdp.proto.v1.TypedValue getFeaturesOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetFeatures().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.TypedValue getFeaturesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetFeatures().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SIGNALS_FIELD_NUMBER = 4;
  private static final class SignalsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.rtdp.proto.v1.ValueMap> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.rtdp.proto.v1.ValueMap>newDefaultInstance(
                com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_SignalsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.rtdp.proto.v1.ValueMap.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.rtdp.proto.v1.ValueMap> signals_;
  private com.google.protobuf.MapField<java.lang.String, com.rtdp.proto.v1.ValueMap>
  internalGetSignals() {
    if (signals_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SignalsDefaultEntryHolder.defaultEntry);
    }
    return signals_;
  }
  public int getSignalsCount() {
    return internalGetSignals().getMap().size();
  }
  /**
   * <pre>
   * alias -&gt; values map for signals that validated OK.
   * </pre>
   *
   * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
   */
  @java.lang.Override
  public boolean containsSignals(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetSignals().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSignalsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap> getSignals() {
    return getSignalsMap();
  }
  /**
   * <pre>
   * alias -&gt; values map for signals that validated OK.
   * </pre>
   *
   * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap> getSignalsMap() {
    return internalGetSignals().getMap();
  }
  /**
   * <pre>
   * alias -&gt; values map for signals that validated OK.
   * </pre>
   *
   * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.rtdp.proto.v1.ValueMap getSignalsOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.ValueMap defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap> map =
        internalGetSignals().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * alias -&gt; values map for signals that validated OK.
   * </pre>
   *
   * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.ValueMap getSignalsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap> map =
        internalGetSignals().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PRESENT_SIGNAL_ALIASES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList presentSignalAliases_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
   * @return A list containing the presentSignalAliases.
   */
  public com.google.protobuf.ProtocolStringList
      getPresentSignalAliasesList() {
    return presentSignalAliases_;
  }
  /**
   * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
   * @return The count of presentSignalAliases.
   */
  public int getPresentSignalAliasesCount() {
    return presentSignalAliases_.size();
  }
  /**
   * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
   * @param index The index of the element to return.
   * @return The presentSignalAliases at the given index.
   */
  public java.lang.String getPresentSignalAliases(int index) {
    return presentSignalAliases_.get(index);
  }
  /**
   * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the presentSignalAliases at the given index.
   */
  public com.google.protobuf.ByteString
      getPresentSignalAliasesBytes(int index) {
    return presentSignalAliases_.getByteString(index);
  }

  public static final int CFG_FIELD_NUMBER = 6;
  private static final class CfgDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.rtdp.proto.v1.TypedValue>newDefaultInstance(
                com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_CfgEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.rtdp.proto.v1.TypedValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.rtdp.proto.v1.TypedValue> cfg_;
  private com.google.protobuf.MapField<java.lang.String, com.rtdp.proto.v1.TypedValue>
  internalGetCfg() {
    if (cfg_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CfgDefaultEntryHolder.defaultEntry);
    }
    return cfg_;
  }
  public int getCfgCount() {
    return internalGetCfg().getMap().size();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
   */
  @java.lang.Override
  public boolean containsCfg(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetCfg().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCfgMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getCfg() {
    return getCfgMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getCfgMap() {
    return internalGetCfg().getMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.rtdp.proto.v1.TypedValue getCfgOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetCfg().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.TypedValue getCfgOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetCfg().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int INPUT_FIELD_NUMBER = 7;
  private static final class InputDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.rtdp.proto.v1.TypedValue>newDefaultInstance(
                com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_InputEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.rtdp.proto.v1.TypedValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.rtdp.proto.v1.TypedValue> input_;
  private com.google.protobuf.MapField<java.lang.String, com.rtdp.proto.v1.TypedValue>
  internalGetInput() {
    if (input_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InputDefaultEntryHolder.defaultEntry);
    }
    return input_;
  }
  public int getInputCount() {
    return internalGetInput().getMap().size();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
   */
  @java.lang.Override
  public boolean containsInput(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetInput().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInputMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getInput() {
    return getInputMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getInputMap() {
    return internalGetInput().getMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.rtdp.proto.v1.TypedValue getInputOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetInput().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.TypedValue getInputOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetInput().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int EXECUTION_BUDGET_MS_FIELD_NUMBER = 8;
  private long executionBudgetMs_ = 0L;
  /**
   * <code>int64 execution_budget_ms = 8 [json_name = "executionBudgetMs"];</code>
   * @return The executionBudgetMs.
   */
  @java.lang.Override
  public long getExecutionBudgetMs() {
    return executionBudgetMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rulesetDigest_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, rulesetDigest_);
    }
    if (!rulesetSpecJson_.isEmpty()) {
      output.writeBytes(2, rulesetSpecJson_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetFeatures(),
        FeaturesDefaultEntryHolder.defaultEntry,
        3);
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetSignals(),
        SignalsDefaultEntryHolder.defaultEntry,
        4);
    for (int i = 0; i < presentSignalAliases_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, presentSignalAliases_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetCfg(),
        CfgDefaultEntryHolder.defaultEntry,
        6);
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetInput(),
        InputDefaultEntryHolder.defaultEntry,
        7);
    if (executionBudgetMs_ != 0L) {
      output.writeInt64(8, executionBudgetMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rulesetDigest_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, rulesetDigest_);
    }
    if (!rulesetSpecJson_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, rulesetSpecJson_);
    }
    for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> entry
         : internalGetFeatures().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
      features__ = FeaturesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, features__);
    }
    for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.ValueMap> entry
         : internalGetSignals().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.ValueMap>
      signals__ = SignalsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, signals__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < presentSignalAliases_.size(); i++) {
        dataSize += computeStringSizeNoTag(presentSignalAliases_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPresentSignalAliasesList().size();
    }
    for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> entry
         : internalGetCfg().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
      cfg__ = CfgDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, cfg__);
    }
    for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> entry
         : internalGetInput().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
      input__ = InputDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, input__);
    }
    if (executionBudgetMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, executionBudgetMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rtdp.proto.v1.EvaluateRulesRequest)) {
      return super.equals(obj);
    }
    com.rtdp.proto.v1.EvaluateRulesRequest other = (com.rtdp.proto.v1.EvaluateRulesRequest) obj;

    if (!getRulesetDigest()
        .equals(other.getRulesetDigest())) return false;
    if (!getRulesetSpecJson()
        .equals(other.getRulesetSpecJson())) return false;
    if (!internalGetFeatures().equals(
        other.internalGetFeatures())) return false;
    if (!internalGetSignals().equals(
        other.internalGetSignals())) return false;
    if (!getPresentSignalAliasesList()
        .equals(other.getPresentSignalAliasesList())) return false;
    if (!internalGetCfg().equals(
        other.internalGetCfg())) return false;
    if (!internalGetInput().equals(
        other.internalGetInput())) return false;
    if (getExecutionBudgetMs()
        != other.getExecutionBudgetMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RULESET_DIGEST_FIELD_NUMBER;
    hash = (53 * hash) + getRulesetDigest().hashCode();
    hash = (37 * hash) + RULESET_SPEC_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getRulesetSpecJson().hashCode();
    if (!internalGetFeatures().getMap().isEmpty()) {
      hash = (37 * hash) + FEATURES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFeatures().hashCode();
    }
    if (!internalGetSignals().getMap().isEmpty()) {
      hash = (37 * hash) + SIGNALS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSignals().hashCode();
    }
    if (getPresentSignalAliasesCount() > 0) {
      hash = (37 * hash) + PRESENT_SIGNAL_ALIASES_FIELD_NUMBER;
      hash = (53 * hash) + getPresentSignalAliasesList().hashCode();
    }
    if (!internalGetCfg().getMap().isEmpty()) {
      hash = (37 * hash) + CFG_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCfg().hashCode();
    }
    if (!internalGetInput().getMap().isEmpty()) {
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInput().hashCode();
    }
    hash = (37 * hash) + EXECUTION_BUDGET_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutionBudgetMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rtdp.proto.v1.EvaluateRulesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rtdp.proto.v1.EvaluateRulesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.EvaluateRulesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rtdp.proto.v1.EvaluateRulesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rtdp.v1.EvaluateRulesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rtdp.v1.EvaluateRulesRequest)
      com.rtdp.proto.v1.EvaluateRulesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetFeatures();
        case 4:
          return internalGetSignals();
        case 6:
          return internalGetCfg();
        case 7:
          return internalGetInput();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableFeatures();
        case 4:
          return internalGetMutableSignals();
        case 6:
          return internalGetMutableCfg();
        case 7:
          return internalGetMutableInput();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rtdp.proto.v1.EvaluateRulesRequest.class, com.rtdp.proto.v1.EvaluateRulesRequest.Builder.class);
    }

    // Construct using com.rtdp.proto.v1.EvaluateRulesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rulesetDigest_ = "";
      rulesetSpecJson_ = com.google.protobuf.ByteString.EMPTY;
      internalGetMutableFeatures().clear();
      internalGetMutableSignals().clear();
      presentSignalAliases_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableCfg().clear();
      internalGetMutableInput().clear();
      executionBudgetMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_EvaluateRulesRequest_descriptor;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.EvaluateRulesRequest getDefaultInstanceForType() {
      return com.rtdp.proto.v1.EvaluateRulesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rtdp.proto.v1.EvaluateRulesRequest build() {
      com.rtdp.proto.v1.EvaluateRulesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.EvaluateRulesRequest buildPartial() {
      com.rtdp.proto.v1.EvaluateRulesRequest result = new com.rtdp.proto.v1.EvaluateRulesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rtdp.proto.v1.EvaluateRulesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rulesetDigest_ = rulesetDigest_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rulesetSpecJson_ = rulesetSpecJson_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.features_ = internalGetFeatures().build(FeaturesDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.signals_ = internalGetSignals().build(SignalsDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        presentSignalAliases_.makeImmutable();
        result.presentSignalAliases_ = presentSignalAliases_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.cfg_ = internalGetCfg().build(CfgDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.input_ = internalGetInput().build(InputDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.executionBudgetMs_ = executionBudgetMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rtdp.proto.v1.EvaluateRulesRequest) {
        return mergeFrom((com.rtdp.proto.v1.EvaluateRulesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rtdp.proto.v1.EvaluateRulesRequest other) {
      if (other == com.rtdp.proto.v1.EvaluateRulesRequest.getDefaultInstance()) return this;
      if (!other.getRulesetDigest().isEmpty()) {
        rulesetDigest_ = other.rulesetDigest_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRulesetSpecJson().isEmpty()) {
        setRulesetSpecJson(other.getRulesetSpecJson());
      }
      internalGetMutableFeatures().mergeFrom(
          other.internalGetFeatures());
      bitField0_ |= 0x00000004;
      internalGetMutableSignals().mergeFrom(
          other.internalGetSignals());
      bitField0_ |= 0x00000008;
      if (!other.presentSignalAliases_.isEmpty()) {
        if (presentSignalAliases_.isEmpty()) {
          presentSignalAliases_ = other.presentSignalAliases_;
          bitField0_ |= 0x00000010;
        } else {
          ensurePresentSignalAliasesIsMutable();
          presentSignalAliases_.addAll(other.presentSignalAliases_);
        }
        onChanged();
      }
      internalGetMutableCfg().mergeFrom(
          other.internalGetCfg());
      bitField0_ |= 0x00000020;
      internalGetMutableInput().mergeFrom(
          other.internalGetInput());
      bitField0_ |= 0x00000040;
      if (other.getExecutionBudgetMs() != 0L) {
        setExecutionBudgetMs(other.getExecutionBudgetMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              rulesetDigest_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              rulesetSpecJson_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
              features__ = input.readMessage(
                  FeaturesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableFeatures().ensureBuilderMap().put(
                  features__.getKey(), features__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.ValueMap>
              signals__ = input.readMessage(
                  SignalsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableSignals().ensureBuilderMap().put(
                  signals__.getKey(), signals__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePresentSignalAliasesIsMutable();
              presentSignalAliases_.add(s);
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
              cfg__ = input.readMessage(
                  CfgDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableCfg().ensureBuilderMap().put(
                  cfg__.getKey(), cfg__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
              input__ = input.readMessage(
                  InputDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableInput().ensureBuilderMap().put(
                  input__.getKey(), input__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              executionBudgetMs_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object rulesetDigest_ = "";
    /**
     * <code>string ruleset_digest = 1 [json_name = "rulesetDigest"];</code>
     * @return The rulesetDigest.
     */
    public java.lang.String getRulesetDigest() {
      java.lang.Object ref = rulesetDigest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rulesetDigest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ruleset_digest = 1 [json_name = "rulesetDigest"];</code>
     * @return The bytes for rulesetDigest.
     */
    public com.google.protobuf.ByteString
        getRulesetDigestBytes() {
      java.lang.Object ref = rulesetDigest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rulesetDigest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ruleset_digest = 1 [json_name = "rulesetDigest"];</code>
     * @param value The rulesetDigest to set.
     * @return This builder for chaining.
     */
    public Builder setRulesetDigest(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rulesetDigest_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string ruleset_digest = 1 [json_name = "rulesetDigest"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRulesetDigest() {
      rulesetDigest_ = getDefaultInstance().getRulesetDigest();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string ruleset_digest = 1 [json_name = "rulesetDigest"];</code>
     * @param value The bytes for rulesetDigest to set.
     * @return This builder for chaining.
     */
    public Builder setRulesetDigestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rulesetDigest_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rulesetSpecJson_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * must sha256-match ruleset_digest
     * </pre>
     *
     * <code>bytes ruleset_spec_json = 2 [json_name = "rulesetSpecJson"];</code>
     * @return The rulesetSpecJson.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRulesetSpecJson() {
      return rulesetSpecJson_;
    }
    /**
     * <pre>
     * must sha256-match ruleset_digest
     * </pre>
     *
     * <code>bytes ruleset_spec_json = 2 [json_name = "rulesetSpecJson"];</code>
     * @param value The rulesetSpecJson to set.
     * @return This builder for chaining.
     */
    public Builder setRulesetSpecJson(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      rulesetSpecJson_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * must sha256-match ruleset_digest
     * </pre>
     *
     * <code>bytes ruleset_spec_json = 2 [json_name = "rulesetSpecJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRulesetSpecJson() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rulesetSpecJson_ = getDefaultInstance().getRulesetSpecJson();
      onChanged();
      return this;
    }

    private static final class FeaturesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue> {
      @java.lang.Override
      public com.rtdp.proto.v1.TypedValue build(com.rtdp.proto.v1.TypedValueOrBuilder val) {
        if (val instanceof com.rtdp.proto.v1.TypedValue) { return (com.rtdp.proto.v1.TypedValue) val; }
        return ((com.rtdp.proto.v1.TypedValue.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry() {
        return FeaturesDefaultEntryHolder.defaultEntry;
      }
    };
    private static final FeaturesConverter featuresConverter = new FeaturesConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder> features_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetFeatures() {
      if (features_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(featuresConverter);
      }
      return features_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetMutableFeatures() {
      if (features_ == null) {
        features_ = new com.google.protobuf.MapFieldBuilder<>(featuresConverter);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return features_;
    }
    public int getFeaturesCount() {
      return internalGetFeatures().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    @java.lang.Override
    public boolean containsFeatures(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFeatures().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getFeaturesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getFeatures() {
      return getFeaturesMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getFeaturesMap() {
      return internalGetFeatures().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.rtdp.proto.v1.TypedValue getFeaturesOrDefault(
        java.lang.String key,
        /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableFeatures().ensureBuilderMap();
      return map.containsKey(key) ? featuresConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    @java.lang.Override
    public com.rtdp.proto.v1.TypedValue getFeaturesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableFeatures().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return featuresConverter.build(map.get(key));
    }
    public Builder clearFeatures() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableFeatures().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    public Builder removeFeatures(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFeatures().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
        getMutableFeatures() {
      bitField0_ |= 0x00000004;
      return internalGetMutableFeatures().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    public Builder putFeatures(
        java.lang.String key,
        com.rtdp.proto.v1.TypedValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableFeatures().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    public Builder putAllFeatures(
        java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> values) {
      for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableFeatures().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 3 [json_name = "features"];</code>
     */
    public com.rtdp.proto.v1.TypedValue.Builder putFeaturesBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> builderMap = internalGetMutableFeatures().ensureBuilderMap();
      com.rtdp.proto.v1.TypedValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.rtdp.proto.v1.TypedValue.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.rtdp.proto.v1.TypedValue) {
        entry = ((com.rtdp.proto.v1.TypedValue) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.rtdp.proto.v1.TypedValue.Builder) entry;
    }

    private static final class SignalsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.rtdp.proto.v1.ValueMapOrBuilder, com.rtdp.proto.v1.ValueMap> {
      @java.lang.Override
      public com.rtdp.proto.v1.ValueMap build(com.rtdp.proto.v1.ValueMapOrBuilder val) {
        if (val instanceof com.rtdp.proto.v1.ValueMap) { return (com.rtdp.proto.v1.ValueMap) val; }
        return ((com.rtdp.proto.v1.ValueMap.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.ValueMap> defaultEntry() {
        return SignalsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final SignalsConverter signalsConverter = new SignalsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.rtdp.proto.v1.ValueMapOrBuilder, com.rtdp.proto.v1.ValueMap, com.rtdp.proto.v1.ValueMap.Builder> signals_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.ValueMapOrBuilder, com.rtdp.proto.v1.ValueMap, com.rtdp.proto.v1.ValueMap.Builder>
        internalGetSignals() {
      if (signals_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(signalsConverter);
      }
      return signals_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.ValueMapOrBuilder, com.rtdp.proto.v1.ValueMap, com.rtdp.proto.v1.ValueMap.Builder>
        internalGetMutableSignals() {
      if (signals_ == null) {
        signals_ = new com.google.protobuf.MapFieldBuilder<>(signalsConverter);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return signals_;
    }
    public int getSignalsCount() {
      return internalGetSignals().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    @java.lang.Override
    public boolean containsSignals(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSignals().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getSignalsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap> getSignals() {
      return getSignalsMap();
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap> getSignalsMap() {
      return internalGetSignals().getImmutableMap();
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.rtdp.proto.v1.ValueMap getSignalsOrDefault(
        java.lang.String key,
        /* nullable */
com.rtdp.proto.v1.ValueMap defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMapOrBuilder> map = internalGetMutableSignals().ensureBuilderMap();
      return map.containsKey(key) ? signalsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    @java.lang.Override
    public com.rtdp.proto.v1.ValueMap getSignalsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMapOrBuilder> map = internalGetMutableSignals().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return signalsConverter.build(map.get(key));
    }
    public Builder clearSignals() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableSignals().clear();
      return this;
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    public Builder removeSignals(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableSignals().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap>
        getMutableSignals() {
      bitField0_ |= 0x00000008;
      return internalGetMutableSignals().ensureMessageMap();
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    public Builder putSignals(
        java.lang.String key,
        com.rtdp.proto.v1.ValueMap value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableSignals().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    public Builder putAllSignals(
        java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMap> values) {
      for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.ValueMap> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableSignals().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <pre>
     * alias -&gt; values map for signals that validated OK.
     * </pre>
     *
     * <code>map&lt;string, .rtdp.v1.ValueMap&gt; signals = 4 [json_name = "signals"];</code>
     */
    public com.rtdp.proto.v1.ValueMap.Builder putSignalsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.rtdp.proto.v1.ValueMapOrBuilder> builderMap = internalGetMutableSignals().ensureBuilderMap();
      com.rtdp.proto.v1.ValueMapOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.rtdp.proto.v1.ValueMap.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.rtdp.proto.v1.ValueMap) {
        entry = ((com.rtdp.proto.v1.ValueMap) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.rtdp.proto.v1.ValueMap.Builder) entry;
    }

    private com.google.protobuf.LazyStringArrayList presentSignalAliases_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePresentSignalAliasesIsMutable() {
      if (!presentSignalAliases_.isModifiable()) {
        presentSignalAliases_ = new com.google.protobuf.LazyStringArrayList(presentSignalAliases_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @return A list containing the presentSignalAliases.
     */
    public com.google.protobuf.ProtocolStringList
        getPresentSignalAliasesList() {
      presentSignalAliases_.makeImmutable();
      return presentSignalAliases_;
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @return The count of presentSignalAliases.
     */
    public int getPresentSignalAliasesCount() {
      return presentSignalAliases_.size();
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @param index The index of the element to return.
     * @return The presentSignalAliases at the given index.
     */
    public java.lang.String getPresentSignalAliases(int index) {
      return presentSignalAliases_.get(index);
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the presentSignalAliases at the given index.
     */
    public com.google.protobuf.ByteString
        getPresentSignalAliasesBytes(int index) {
      return presentSignalAliases_.getByteString(index);
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @param index The index to set the value at.
     * @param value The presentSignalAliases to set.
     * @return This builder for chaining.
     */
    public Builder setPresentSignalAliases(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePresentSignalAliasesIsMutable();
      presentSignalAliases_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @param value The presentSignalAliases to add.
     * @return This builder for chaining.
     */
    public Builder addPresentSignalAliases(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePresentSignalAliasesIsMutable();
      presentSignalAliases_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @param values The presentSignalAliases to add.
     * @return This builder for chaining.
     */
    public Builder addAllPresentSignalAliases(
        java.lang.Iterable<java.lang.String> values) {
      ensurePresentSignalAliasesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, presentSignalAliases_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPresentSignalAliases() {
      presentSignalAliases_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string present_signal_aliases = 5 [json_name = "presentSignalAliases"];</code>
     * @param value The bytes of the presentSignalAliases to add.
     * @return This builder for chaining.
     */
    public Builder addPresentSignalAliasesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensurePresentSignalAliasesIsMutable();
      presentSignalAliases_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private static final class CfgConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue> {
      @java.lang.Override
      public com.rtdp.proto.v1.TypedValue build(com.rtdp.proto.v1.TypedValueOrBuilder val) {
        if (val instanceof com.rtdp.proto.v1.TypedValue) { return (com.rtdp.proto.v1.TypedValue) val; }
        return ((com.rtdp.proto.v1.TypedValue.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry() {
        return CfgDefaultEntryHolder.defaultEntry;
      }
    };
    private static final CfgConverter cfgConverter = new CfgConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder> cfg_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetCfg() {
      if (cfg_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(cfgConverter);
      }
      return cfg_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetMutableCfg() {
      if (cfg_ == null) {
        cfg_ = new com.google.protobuf.MapFieldBuilder<>(cfgConverter);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return cfg_;
    }
    public int getCfgCount() {
      return internalGetCfg().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    @java.lang.Override
    public boolean containsCfg(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCfg().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getCfgMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getCfg() {
      return getCfgMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getCfgMap() {
      return internalGetCfg().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.rtdp.proto.v1.TypedValue getCfgOrDefault(
        java.lang.String key,
        /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableCfg().ensureBuilderMap();
      return map.containsKey(key) ? cfgConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    @java.lang.Override
    public com.rtdp.proto.v1.TypedValue getCfgOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableCfg().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return cfgConverter.build(map.get(key));
    }
    public Builder clearCfg() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableCfg().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    public Builder removeCfg(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableCfg().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
        getMutableCfg() {
      bitField0_ |= 0x00000020;
      return internalGetMutableCfg().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    public Builder putCfg(
        java.lang.String key,
        com.rtdp.proto.v1.TypedValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableCfg().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    public Builder putAllCfg(
        java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> values) {
      for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableCfg().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; cfg = 6 [json_name = "cfg"];</code>
     */
    public com.rtdp.proto.v1.TypedValue.Builder putCfgBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> builderMap = internalGetMutableCfg().ensureBuilderMap();
      com.rtdp.proto.v1.TypedValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.rtdp.proto.v1.TypedValue.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.rtdp.proto.v1.TypedValue) {
        entry = ((com.rtdp.proto.v1.TypedValue) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.rtdp.proto.v1.TypedValue.Builder) entry;
    }

    private static final class InputConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue> {
      @java.lang.Override
      public com.rtdp.proto.v1.TypedValue build(com.rtdp.proto.v1.TypedValueOrBuilder val) {
        if (val instanceof com.rtdp.proto.v1.TypedValue) { return (com.rtdp.proto.v1.TypedValue) val; }
        return ((com.rtdp.proto.v1.TypedValue.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry() {
        return InputDefaultEntryHolder.defaultEntry;
      }
    };
    private static final InputConverter inputConverter = new InputConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder> input_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetInput() {
      if (input_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(inputConverter);
      }
      return input_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetMutableInput() {
      if (input_ == null) {
        input_ = new com.google.protobuf.MapFieldBuilder<>(inputConverter);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return input_;
    }
    public int getInputCount() {
      return internalGetInput().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    @java.lang.Override
    public boolean containsInput(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetInput().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getInputMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getInput() {
      return getInputMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getInputMap() {
      return internalGetInput().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.rtdp.proto.v1.TypedValue getInputOrDefault(
        java.lang.String key,
        /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableInput().ensureBuilderMap();
      return map.containsKey(key) ? inputConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    @java.lang.Override
    public com.rtdp.proto.v1.TypedValue getInputOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableInput().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return inputConverter.build(map.get(key));
    }
    public Builder clearInput() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableInput().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    public Builder removeInput(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableInput().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
        getMutableInput() {
      bitField0_ |= 0x00000040;
      return internalGetMutableInput().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    public Builder putInput(
        java.lang.String key,
        com.rtdp.proto.v1.TypedValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableInput().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    public Builder putAllInput(
        java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> values) {
      for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableInput().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; input = 7 [json_name = "input"];</code>
     */
    public com.rtdp.proto.v1.TypedValue.Builder putInputBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> builderMap = internalGetMutableInput().ensureBuilderMap();
      com.rtdp.proto.v1.TypedValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.rtdp.proto.v1.TypedValue.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.rtdp.proto.v1.TypedValue) {
        entry = ((com.rtdp.proto.v1.TypedValue) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.rtdp.proto.v1.TypedValue.Builder) entry;
    }

    private long executionBudgetMs_ ;
    /**
     * <code>int64 execution_budget_ms = 8 [json_name = "executionBudgetMs"];</code>
     * @return The executionBudgetMs.
     */
    @java.lang.Override
    public long getExecutionBudgetMs() {
      return executionBudgetMs_;
    }
    /**
     * <code>int64 execution_budget_ms = 8 [json_name = "executionBudgetMs"];</code>
     * @param value The executionBudgetMs to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionBudgetMs(long value) {

      executionBudgetMs_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 execution_budget_ms = 8 [json_name = "executionBudgetMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionBudgetMs() {
      bitField0_ = (bitField0_ & ~0x00000080);
      executionBudgetMs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rtdp.v1.EvaluateRulesRequest)
  }

  // @@protoc_insertion_point(class_scope:rtdp.v1.EvaluateRulesRequest)
  private static final com.rtdp.proto.v1.EvaluateRulesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rtdp.proto.v1.EvaluateRulesRequest();
  }

  public static com.rtdp.proto.v1.EvaluateRulesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EvaluateRulesRequest>
      PARSER = new com.google.protobuf.AbstractParser<EvaluateRulesRequest>() {
    @java.lang.Override
    public EvaluateRulesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EvaluateRulesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EvaluateRulesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rtdp.proto.v1.EvaluateRulesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

