// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/decision.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * <pre>
 * FeatureContribution is the canonical per-event input to streaming features.
 * One contribution per accepted event regardless of product fan-out.
 * </pre>
 *
 * Protobuf type {@code rtdp.v1.FeatureContribution}
 */
@com.google.protobuf.Generated
public final class FeatureContribution extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rtdp.v1.FeatureContribution)
    FeatureContributionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "FeatureContribution");
  }
  // Use FeatureContribution.newBuilder() to construct.
  private FeatureContribution(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FeatureContribution() {
    contributionId_ = "";
    tenantId_ = "";
    environment_ = "";
    mode_ = 0;
    transactionId_ = "";
    tokenizedClaimant_ = "";
    providerId_ = "";
    currency_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_FeatureContribution_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_FeatureContribution_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rtdp.proto.v1.FeatureContribution.class, com.rtdp.proto.v1.FeatureContribution.Builder.class);
  }

  private int bitField0_;
  public static final int CONTRIBUTION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contributionId_ = "";
  /**
   * <code>string contribution_id = 1 [json_name = "contributionId"];</code>
   * @return The contributionId.
   */
  @java.lang.Override
  public java.lang.String getContributionId() {
    java.lang.Object ref = contributionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contributionId_ = s;
      return s;
    }
  }
  /**
   * <code>string contribution_id = 1 [json_name = "contributionId"];</code>
   * @return The bytes for contributionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContributionIdBytes() {
    java.lang.Object ref = contributionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contributionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENVIRONMENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object environment_ = "";
  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The environment.
   */
  @java.lang.Override
  public java.lang.String getEnvironment() {
    java.lang.Object ref = environment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      environment_ = s;
      return s;
    }
  }
  /**
   * <code>string environment = 3 [json_name = "environment"];</code>
   * @return The bytes for environment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvironmentBytes() {
    java.lang.Object ref = environment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      environment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODE_FIELD_NUMBER = 4;
  private int mode_ = 0;
  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The enum numeric value on the wire for mode.
   */
  @java.lang.Override public int getModeValue() {
    return mode_;
  }
  /**
   * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
   * @return The mode.
   */
  @java.lang.Override public com.rtdp.proto.v1.Mode getMode() {
    com.rtdp.proto.v1.Mode result = com.rtdp.proto.v1.Mode.forNumber(mode_);
    return result == null ? com.rtdp.proto.v1.Mode.UNRECOGNIZED : result;
  }

  public static final int TRANSACTION_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transactionId_ = "";
  /**
   * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
   * @return The transactionId.
   */
  @java.lang.Override
  public java.lang.String getTransactionId() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionId_ = s;
      return s;
    }
  }
  /**
   * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
   * @return The bytes for transactionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTION_REVISION_FIELD_NUMBER = 6;
  private long transactionRevision_ = 0L;
  /**
   * <code>int64 transaction_revision = 6 [json_name = "transactionRevision"];</code>
   * @return The transactionRevision.
   */
  @java.lang.Override
  public long getTransactionRevision() {
    return transactionRevision_;
  }

  public static final int TOKENIZED_CLAIMANT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tokenizedClaimant_ = "";
  /**
   * <code>string tokenized_claimant = 7 [json_name = "tokenizedClaimant"];</code>
   * @return The tokenizedClaimant.
   */
  @java.lang.Override
  public java.lang.String getTokenizedClaimant() {
    java.lang.Object ref = tokenizedClaimant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tokenizedClaimant_ = s;
      return s;
    }
  }
  /**
   * <code>string tokenized_claimant = 7 [json_name = "tokenizedClaimant"];</code>
   * @return The bytes for tokenizedClaimant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenizedClaimantBytes() {
    java.lang.Object ref = tokenizedClaimant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tokenizedClaimant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVIDER_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object providerId_ = "";
  /**
   * <code>string provider_id = 8 [json_name = "providerId"];</code>
   * @return The providerId.
   */
  @java.lang.Override
  public java.lang.String getProviderId() {
    java.lang.Object ref = providerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      providerId_ = s;
      return s;
    }
  }
  /**
   * <code>string provider_id = 8 [json_name = "providerId"];</code>
   * @return The bytes for providerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProviderIdBytes() {
    java.lang.Object ref = providerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      providerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENCY_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currency_ = "";
  /**
   * <code>string currency = 9 [json_name = "currency"];</code>
   * @return The currency.
   */
  @java.lang.Override
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <code>string currency = 9 [json_name = "currency"];</code>
   * @return The bytes for currency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 10;
  private double amount_ = 0D;
  /**
   * <code>double amount = 10 [json_name = "amount"];</code>
   * @return The amount.
   */
  @java.lang.Override
  public double getAmount() {
    return amount_;
  }

  public static final int EVENT_TIME_FIELD_NUMBER = 11;
  private com.google.protobuf.Timestamp eventTime_;
  /**
   * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
   * @return Whether the eventTime field is set.
   */
  @java.lang.Override
  public boolean hasEventTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
   * @return The eventTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEventTime() {
    return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder() {
    return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contributionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, contributionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(environment_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, environment_);
    }
    if (mode_ != com.rtdp.proto.v1.Mode.MODE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, mode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, transactionId_);
    }
    if (transactionRevision_ != 0L) {
      output.writeInt64(6, transactionRevision_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tokenizedClaimant_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, tokenizedClaimant_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(providerId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, providerId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, currency_);
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      output.writeDouble(10, amount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(11, getEventTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contributionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, contributionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(environment_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, environment_);
    }
    if (mode_ != com.rtdp.proto.v1.Mode.MODE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, mode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, transactionId_);
    }
    if (transactionRevision_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, transactionRevision_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tokenizedClaimant_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, tokenizedClaimant_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(providerId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, providerId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, currency_);
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, amount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getEventTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rtdp.proto.v1.FeatureContribution)) {
      return super.equals(obj);
    }
    com.rtdp.proto.v1.FeatureContribution other = (com.rtdp.proto.v1.FeatureContribution) obj;

    if (!getContributionId()
        .equals(other.getContributionId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getEnvironment()
        .equals(other.getEnvironment())) return false;
    if (mode_ != other.mode_) return false;
    if (!getTransactionId()
        .equals(other.getTransactionId())) return false;
    if (getTransactionRevision()
        != other.getTransactionRevision()) return false;
    if (!getTokenizedClaimant()
        .equals(other.getTokenizedClaimant())) return false;
    if (!getProviderId()
        .equals(other.getProviderId())) return false;
    if (!getCurrency()
        .equals(other.getCurrency())) return false;
    if (java.lang.Double.doubleToLongBits(getAmount())
        != java.lang.Double.doubleToLongBits(
            other.getAmount())) return false;
    if (hasEventTime() != other.hasEventTime()) return false;
    if (hasEventTime()) {
      if (!getEventTime()
          .equals(other.getEventTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRIBUTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getContributionId().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + ENVIRONMENT_FIELD_NUMBER;
    hash = (53 * hash) + getEnvironment().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + mode_;
    hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionId().hashCode();
    hash = (37 * hash) + TRANSACTION_REVISION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTransactionRevision());
    hash = (37 * hash) + TOKENIZED_CLAIMANT_FIELD_NUMBER;
    hash = (53 * hash) + getTokenizedClaimant().hashCode();
    hash = (37 * hash) + PROVIDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProviderId().hashCode();
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    if (hasEventTime()) {
      hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEventTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rtdp.proto.v1.FeatureContribution parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rtdp.proto.v1.FeatureContribution parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.FeatureContribution parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rtdp.proto.v1.FeatureContribution prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FeatureContribution is the canonical per-event input to streaming features.
   * One contribution per accepted event regardless of product fan-out.
   * </pre>
   *
   * Protobuf type {@code rtdp.v1.FeatureContribution}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rtdp.v1.FeatureContribution)
      com.rtdp.proto.v1.FeatureContributionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_FeatureContribution_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_FeatureContribution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rtdp.proto.v1.FeatureContribution.class, com.rtdp.proto.v1.FeatureContribution.Builder.class);
    }

    // Construct using com.rtdp.proto.v1.FeatureContribution.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetEventTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contributionId_ = "";
      tenantId_ = "";
      environment_ = "";
      mode_ = 0;
      transactionId_ = "";
      transactionRevision_ = 0L;
      tokenizedClaimant_ = "";
      providerId_ = "";
      currency_ = "";
      amount_ = 0D;
      eventTime_ = null;
      if (eventTimeBuilder_ != null) {
        eventTimeBuilder_.dispose();
        eventTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rtdp.proto.v1.DecisionProtos.internal_static_rtdp_v1_FeatureContribution_descriptor;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.FeatureContribution getDefaultInstanceForType() {
      return com.rtdp.proto.v1.FeatureContribution.getDefaultInstance();
    }

    @java.lang.Override
    public com.rtdp.proto.v1.FeatureContribution build() {
      com.rtdp.proto.v1.FeatureContribution result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.FeatureContribution buildPartial() {
      com.rtdp.proto.v1.FeatureContribution result = new com.rtdp.proto.v1.FeatureContribution(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rtdp.proto.v1.FeatureContribution result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contributionId_ = contributionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.environment_ = environment_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mode_ = mode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.transactionId_ = transactionId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.transactionRevision_ = transactionRevision_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.tokenizedClaimant_ = tokenizedClaimant_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.providerId_ = providerId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.currency_ = currency_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.amount_ = amount_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.eventTime_ = eventTimeBuilder_ == null
            ? eventTime_
            : eventTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rtdp.proto.v1.FeatureContribution) {
        return mergeFrom((com.rtdp.proto.v1.FeatureContribution)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rtdp.proto.v1.FeatureContribution other) {
      if (other == com.rtdp.proto.v1.FeatureContribution.getDefaultInstance()) return this;
      if (!other.getContributionId().isEmpty()) {
        contributionId_ = other.contributionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEnvironment().isEmpty()) {
        environment_ = other.environment_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.mode_ != 0) {
        setModeValue(other.getModeValue());
      }
      if (!other.getTransactionId().isEmpty()) {
        transactionId_ = other.transactionId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTransactionRevision() != 0L) {
        setTransactionRevision(other.getTransactionRevision());
      }
      if (!other.getTokenizedClaimant().isEmpty()) {
        tokenizedClaimant_ = other.tokenizedClaimant_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getProviderId().isEmpty()) {
        providerId_ = other.providerId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getAmount()) != 0) {
        setAmount(other.getAmount());
      }
      if (other.hasEventTime()) {
        mergeEventTime(other.getEventTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contributionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              environment_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              mode_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              transactionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              transactionRevision_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              tokenizedClaimant_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              providerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              currency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 81: {
              amount_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 90: {
              input.readMessage(
                  internalGetEventTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contributionId_ = "";
    /**
     * <code>string contribution_id = 1 [json_name = "contributionId"];</code>
     * @return The contributionId.
     */
    public java.lang.String getContributionId() {
      java.lang.Object ref = contributionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contributionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contribution_id = 1 [json_name = "contributionId"];</code>
     * @return The bytes for contributionId.
     */
    public com.google.protobuf.ByteString
        getContributionIdBytes() {
      java.lang.Object ref = contributionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contributionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contribution_id = 1 [json_name = "contributionId"];</code>
     * @param value The contributionId to set.
     * @return This builder for chaining.
     */
    public Builder setContributionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contributionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string contribution_id = 1 [json_name = "contributionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearContributionId() {
      contributionId_ = getDefaultInstance().getContributionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string contribution_id = 1 [json_name = "contributionId"];</code>
     * @param value The bytes for contributionId to set.
     * @return This builder for chaining.
     */
    public Builder setContributionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contributionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 2 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object environment_ = "";
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @return The environment.
     */
    public java.lang.String getEnvironment() {
      java.lang.Object ref = environment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        environment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @return The bytes for environment.
     */
    public com.google.protobuf.ByteString
        getEnvironmentBytes() {
      java.lang.Object ref = environment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        environment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @param value The environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironment(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      environment_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironment() {
      environment_ = getDefaultInstance().getEnvironment();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string environment = 3 [json_name = "environment"];</code>
     * @param value The bytes for environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      environment_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int mode_ = 0;
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @return The enum numeric value on the wire for mode.
     */
    @java.lang.Override public int getModeValue() {
      return mode_;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @param value The enum numeric value on the wire for mode to set.
     * @return This builder for chaining.
     */
    public Builder setModeValue(int value) {
      mode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @return The mode.
     */
    @java.lang.Override
    public com.rtdp.proto.v1.Mode getMode() {
      com.rtdp.proto.v1.Mode result = com.rtdp.proto.v1.Mode.forNumber(mode_);
      return result == null ? com.rtdp.proto.v1.Mode.UNRECOGNIZED : result;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(com.rtdp.proto.v1.Mode value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      mode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.rtdp.v1.Mode mode = 4 [json_name = "mode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      mode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object transactionId_ = "";
    /**
     * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
     * @return The transactionId.
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
     * @return The bytes for transactionId.
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
     * @param value The transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionId() {
      transactionId_ = getDefaultInstance().getTransactionId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 5 [json_name = "transactionId"];</code>
     * @param value The bytes for transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long transactionRevision_ ;
    /**
     * <code>int64 transaction_revision = 6 [json_name = "transactionRevision"];</code>
     * @return The transactionRevision.
     */
    @java.lang.Override
    public long getTransactionRevision() {
      return transactionRevision_;
    }
    /**
     * <code>int64 transaction_revision = 6 [json_name = "transactionRevision"];</code>
     * @param value The transactionRevision to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionRevision(long value) {

      transactionRevision_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 transaction_revision = 6 [json_name = "transactionRevision"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionRevision() {
      bitField0_ = (bitField0_ & ~0x00000020);
      transactionRevision_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object tokenizedClaimant_ = "";
    /**
     * <code>string tokenized_claimant = 7 [json_name = "tokenizedClaimant"];</code>
     * @return The tokenizedClaimant.
     */
    public java.lang.String getTokenizedClaimant() {
      java.lang.Object ref = tokenizedClaimant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenizedClaimant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tokenized_claimant = 7 [json_name = "tokenizedClaimant"];</code>
     * @return The bytes for tokenizedClaimant.
     */
    public com.google.protobuf.ByteString
        getTokenizedClaimantBytes() {
      java.lang.Object ref = tokenizedClaimant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenizedClaimant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tokenized_claimant = 7 [json_name = "tokenizedClaimant"];</code>
     * @param value The tokenizedClaimant to set.
     * @return This builder for chaining.
     */
    public Builder setTokenizedClaimant(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tokenizedClaimant_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string tokenized_claimant = 7 [json_name = "tokenizedClaimant"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenizedClaimant() {
      tokenizedClaimant_ = getDefaultInstance().getTokenizedClaimant();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string tokenized_claimant = 7 [json_name = "tokenizedClaimant"];</code>
     * @param value The bytes for tokenizedClaimant to set.
     * @return This builder for chaining.
     */
    public Builder setTokenizedClaimantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tokenizedClaimant_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object providerId_ = "";
    /**
     * <code>string provider_id = 8 [json_name = "providerId"];</code>
     * @return The providerId.
     */
    public java.lang.String getProviderId() {
      java.lang.Object ref = providerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        providerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string provider_id = 8 [json_name = "providerId"];</code>
     * @return The bytes for providerId.
     */
    public com.google.protobuf.ByteString
        getProviderIdBytes() {
      java.lang.Object ref = providerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        providerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string provider_id = 8 [json_name = "providerId"];</code>
     * @param value The providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      providerId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string provider_id = 8 [json_name = "providerId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderId() {
      providerId_ = getDefaultInstance().getProviderId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string provider_id = 8 [json_name = "providerId"];</code>
     * @param value The bytes for providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      providerId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <code>string currency = 9 [json_name = "currency"];</code>
     * @return The currency.
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currency = 9 [json_name = "currency"];</code>
     * @return The bytes for currency.
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currency = 9 [json_name = "currency"];</code>
     * @param value The currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currency_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string currency = 9 [json_name = "currency"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrency() {
      currency_ = getDefaultInstance().getCurrency();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string currency = 9 [json_name = "currency"];</code>
     * @param value The bytes for currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currency_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>double amount = 10 [json_name = "amount"];</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 10 [json_name = "amount"];</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {

      amount_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 10 [json_name = "amount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000200);
      amount_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp eventTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> eventTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     * @return Whether the eventTime field is set.
     */
    public boolean hasEventTime() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     * @return The eventTime.
     */
    public com.google.protobuf.Timestamp getEventTime() {
      if (eventTimeBuilder_ == null) {
        return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
      } else {
        return eventTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     */
    public Builder setEventTime(com.google.protobuf.Timestamp value) {
      if (eventTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventTime_ = value;
      } else {
        eventTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     */
    public Builder setEventTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (eventTimeBuilder_ == null) {
        eventTime_ = builderForValue.build();
      } else {
        eventTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     */
    public Builder mergeEventTime(com.google.protobuf.Timestamp value) {
      if (eventTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          eventTime_ != null &&
          eventTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getEventTimeBuilder().mergeFrom(value);
        } else {
          eventTime_ = value;
        }
      } else {
        eventTimeBuilder_.mergeFrom(value);
      }
      if (eventTime_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     */
    public Builder clearEventTime() {
      bitField0_ = (bitField0_ & ~0x00000400);
      eventTime_ = null;
      if (eventTimeBuilder_ != null) {
        eventTimeBuilder_.dispose();
        eventTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getEventTimeBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return internalGetEventTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder() {
      if (eventTimeBuilder_ != null) {
        return eventTimeBuilder_.getMessageOrBuilder();
      } else {
        return eventTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 11 [json_name = "eventTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetEventTimeFieldBuilder() {
      if (eventTimeBuilder_ == null) {
        eventTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEventTime(),
                getParentForChildren(),
                isClean());
        eventTime_ = null;
      }
      return eventTimeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:rtdp.v1.FeatureContribution)
  }

  // @@protoc_insertion_point(class_scope:rtdp.v1.FeatureContribution)
  private static final com.rtdp.proto.v1.FeatureContribution DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rtdp.proto.v1.FeatureContribution();
  }

  public static com.rtdp.proto.v1.FeatureContribution getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeatureContribution>
      PARSER = new com.google.protobuf.AbstractParser<FeatureContribution>() {
    @java.lang.Override
    public FeatureContribution parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FeatureContribution> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeatureContribution> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rtdp.proto.v1.FeatureContribution getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

