// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/decision.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * <pre>
 * IntentStatus is the release state of an intent/command (ADR-014).
 * </pre>
 *
 * Protobuf enum {@code rtdp.v1.IntentStatus}
 */
@com.google.protobuf.Generated
public enum IntentStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INTENT_STATUS_UNSPECIFIED = 0;</code>
   */
  INTENT_STATUS_UNSPECIFIED(0),
  /**
   * <pre>
   * free to dispatch
   * </pre>
   *
   * <code>INTENT_READY = 1;</code>
   */
  INTENT_READY(1),
  /**
   * <pre>
   * held: a human must approve first
   * </pre>
   *
   * <code>INTENT_AWAITING_APPROVAL = 2;</code>
   */
  INTENT_AWAITING_APPROVAL(2),
  /**
   * <pre>
   * approval rejected — never dispatches
   * </pre>
   *
   * <code>INTENT_CANCELLED = 3;</code>
   */
  INTENT_CANCELLED(3),
  /**
   * <pre>
   * approval SLA breached with EXPIRE
   * </pre>
   *
   * <code>INTENT_EXPIRED = 4;</code>
   */
  INTENT_EXPIRED(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "IntentStatus");
  }
  /**
   * <code>INTENT_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int INTENT_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * free to dispatch
   * </pre>
   *
   * <code>INTENT_READY = 1;</code>
   */
  public static final int INTENT_READY_VALUE = 1;
  /**
   * <pre>
   * held: a human must approve first
   * </pre>
   *
   * <code>INTENT_AWAITING_APPROVAL = 2;</code>
   */
  public static final int INTENT_AWAITING_APPROVAL_VALUE = 2;
  /**
   * <pre>
   * approval rejected — never dispatches
   * </pre>
   *
   * <code>INTENT_CANCELLED = 3;</code>
   */
  public static final int INTENT_CANCELLED_VALUE = 3;
  /**
   * <pre>
   * approval SLA breached with EXPIRE
   * </pre>
   *
   * <code>INTENT_EXPIRED = 4;</code>
   */
  public static final int INTENT_EXPIRED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static IntentStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static IntentStatus forNumber(int value) {
    switch (value) {
      case 0: return INTENT_STATUS_UNSPECIFIED;
      case 1: return INTENT_READY;
      case 2: return INTENT_AWAITING_APPROVAL;
      case 3: return INTENT_CANCELLED;
      case 4: return INTENT_EXPIRED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<IntentStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      IntentStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<IntentStatus>() {
          public IntentStatus findValueByNumber(int number) {
            return IntentStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.rtdp.proto.v1.DecisionProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final IntentStatus[] VALUES = values();

  public static IntentStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private IntentStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:rtdp.v1.IntentStatus)
}

