// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/envelope.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * <pre>
 * Execution mode isolates live traffic from evaluation.
 * </pre>
 *
 * Protobuf enum {@code rtdp.v1.Mode}
 */
@com.google.protobuf.Generated
public enum Mode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MODE_UNSPECIFIED = 0;</code>
   */
  MODE_UNSPECIFIED(0),
  /**
   * <code>MODE_LIVE = 1;</code>
   */
  MODE_LIVE(1),
  /**
   * <code>MODE_SHADOW = 2;</code>
   */
  MODE_SHADOW(2),
  /**
   * <code>MODE_REPLAY = 3;</code>
   */
  MODE_REPLAY(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Mode");
  }
  /**
   * <code>MODE_UNSPECIFIED = 0;</code>
   */
  public static final int MODE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MODE_LIVE = 1;</code>
   */
  public static final int MODE_LIVE_VALUE = 1;
  /**
   * <code>MODE_SHADOW = 2;</code>
   */
  public static final int MODE_SHADOW_VALUE = 2;
  /**
   * <code>MODE_REPLAY = 3;</code>
   */
  public static final int MODE_REPLAY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Mode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Mode forNumber(int value) {
    switch (value) {
      case 0: return MODE_UNSPECIFIED;
      case 1: return MODE_LIVE;
      case 2: return MODE_SHADOW;
      case 3: return MODE_REPLAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Mode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Mode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Mode>() {
          public Mode findValueByNumber(int number) {
            return Mode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.rtdp.proto.v1.Envelope.getDescriptor().getEnumTypes().get(0);
  }

  private static final Mode[] VALUES = values();

  public static Mode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Mode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:rtdp.v1.Mode)
}

