// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/services.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface ResolveFeaturesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.ResolveFeaturesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 1 [json_name = "features"];</code>
   */
  int getFeaturesCount();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 1 [json_name = "features"];</code>
   */
  boolean containsFeatures(
      java.lang.String key);
  /**
   * Use {@link #getFeaturesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getFeatures();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 1 [json_name = "features"];</code>
   */
  java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
  getFeaturesMap();
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 1 [json_name = "features"];</code>
   */
  /* nullable */
com.rtdp.proto.v1.TypedValue getFeaturesOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue);
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; features = 1 [json_name = "features"];</code>
   */
  com.rtdp.proto.v1.TypedValue getFeaturesOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string missing_features = 2 [json_name = "missingFeatures"];</code>
   * @return A list containing the missingFeatures.
   */
  java.util.List<java.lang.String>
      getMissingFeaturesList();
  /**
   * <code>repeated string missing_features = 2 [json_name = "missingFeatures"];</code>
   * @return The count of missingFeatures.
   */
  int getMissingFeaturesCount();
  /**
   * <code>repeated string missing_features = 2 [json_name = "missingFeatures"];</code>
   * @param index The index of the element to return.
   * @return The missingFeatures at the given index.
   */
  java.lang.String getMissingFeatures(int index);
  /**
   * <code>repeated string missing_features = 2 [json_name = "missingFeatures"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the missingFeatures at the given index.
   */
  com.google.protobuf.ByteString
      getMissingFeaturesBytes(int index);

  /**
   * <code>string snapshot_digest = 3 [json_name = "snapshotDigest"];</code>
   * @return The snapshotDigest.
   */
  java.lang.String getSnapshotDigest();
  /**
   * <code>string snapshot_digest = 3 [json_name = "snapshotDigest"];</code>
   * @return The bytes for snapshotDigest.
   */
  com.google.protobuf.ByteString
      getSnapshotDigestBytes();
}
