// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/services.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * Protobuf type {@code rtdp.v1.ResolvedSignal}
 */
@com.google.protobuf.Generated
public final class ResolvedSignal extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rtdp.v1.ResolvedSignal)
    ResolvedSignalOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ResolvedSignal");
  }
  // Use ResolvedSignal.newBuilder() to construct.
  private ResolvedSignal(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResolvedSignal() {
    alias_ = "";
    rejectCode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_ResolvedSignal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_ResolvedSignal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rtdp.proto.v1.ResolvedSignal.class, com.rtdp.proto.v1.ResolvedSignal.Builder.class);
  }

  private int bitField0_;
  public static final int ALIAS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alias_ = "";
  /**
   * <code>string alias = 1 [json_name = "alias"];</code>
   * @return The alias.
   */
  @java.lang.Override
  public java.lang.String getAlias() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alias_ = s;
      return s;
    }
  }
  /**
   * <code>string alias = 1 [json_name = "alias"];</code>
   * @return The bytes for alias.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasBytes() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENVELOPE_FIELD_NUMBER = 2;
  private com.rtdp.proto.v1.SignalEnvelope envelope_;
  /**
   * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
   * @return Whether the envelope field is set.
   */
  @java.lang.Override
  public boolean hasEnvelope() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
   * @return The envelope.
   */
  @java.lang.Override
  public com.rtdp.proto.v1.SignalEnvelope getEnvelope() {
    return envelope_ == null ? com.rtdp.proto.v1.SignalEnvelope.getDefaultInstance() : envelope_;
  }
  /**
   * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.SignalEnvelopeOrBuilder getEnvelopeOrBuilder() {
    return envelope_ == null ? com.rtdp.proto.v1.SignalEnvelope.getDefaultInstance() : envelope_;
  }

  public static final int OK_FIELD_NUMBER = 3;
  private boolean ok_ = false;
  /**
   * <pre>
   * envelope validated + status OK
   * </pre>
   *
   * <code>bool ok = 3 [json_name = "ok"];</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }

  public static final int REJECT_CODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rejectCode_ = "";
  /**
   * <code>string reject_code = 4 [json_name = "rejectCode"];</code>
   * @return The rejectCode.
   */
  @java.lang.Override
  public java.lang.String getRejectCode() {
    java.lang.Object ref = rejectCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rejectCode_ = s;
      return s;
    }
  }
  /**
   * <code>string reject_code = 4 [json_name = "rejectCode"];</code>
   * @return The bytes for rejectCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRejectCodeBytes() {
    java.lang.Object ref = rejectCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rejectCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alias_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, alias_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getEnvelope());
    }
    if (ok_ != false) {
      output.writeBool(3, ok_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rejectCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, rejectCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alias_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, alias_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEnvelope());
    }
    if (ok_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, ok_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rejectCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, rejectCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rtdp.proto.v1.ResolvedSignal)) {
      return super.equals(obj);
    }
    com.rtdp.proto.v1.ResolvedSignal other = (com.rtdp.proto.v1.ResolvedSignal) obj;

    if (!getAlias()
        .equals(other.getAlias())) return false;
    if (hasEnvelope() != other.hasEnvelope()) return false;
    if (hasEnvelope()) {
      if (!getEnvelope()
          .equals(other.getEnvelope())) return false;
    }
    if (getOk()
        != other.getOk()) return false;
    if (!getRejectCode()
        .equals(other.getRejectCode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getAlias().hashCode();
    if (hasEnvelope()) {
      hash = (37 * hash) + ENVELOPE_FIELD_NUMBER;
      hash = (53 * hash) + getEnvelope().hashCode();
    }
    hash = (37 * hash) + OK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOk());
    hash = (37 * hash) + REJECT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRejectCode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rtdp.proto.v1.ResolvedSignal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rtdp.proto.v1.ResolvedSignal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ResolvedSignal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rtdp.proto.v1.ResolvedSignal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rtdp.v1.ResolvedSignal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rtdp.v1.ResolvedSignal)
      com.rtdp.proto.v1.ResolvedSignalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_ResolvedSignal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_ResolvedSignal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rtdp.proto.v1.ResolvedSignal.class, com.rtdp.proto.v1.ResolvedSignal.Builder.class);
    }

    // Construct using com.rtdp.proto.v1.ResolvedSignal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetEnvelopeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      alias_ = "";
      envelope_ = null;
      if (envelopeBuilder_ != null) {
        envelopeBuilder_.dispose();
        envelopeBuilder_ = null;
      }
      ok_ = false;
      rejectCode_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rtdp.proto.v1.ServicesProtos.internal_static_rtdp_v1_ResolvedSignal_descriptor;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ResolvedSignal getDefaultInstanceForType() {
      return com.rtdp.proto.v1.ResolvedSignal.getDefaultInstance();
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ResolvedSignal build() {
      com.rtdp.proto.v1.ResolvedSignal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ResolvedSignal buildPartial() {
      com.rtdp.proto.v1.ResolvedSignal result = new com.rtdp.proto.v1.ResolvedSignal(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rtdp.proto.v1.ResolvedSignal result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.alias_ = alias_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.envelope_ = envelopeBuilder_ == null
            ? envelope_
            : envelopeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ok_ = ok_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.rejectCode_ = rejectCode_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rtdp.proto.v1.ResolvedSignal) {
        return mergeFrom((com.rtdp.proto.v1.ResolvedSignal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rtdp.proto.v1.ResolvedSignal other) {
      if (other == com.rtdp.proto.v1.ResolvedSignal.getDefaultInstance()) return this;
      if (!other.getAlias().isEmpty()) {
        alias_ = other.alias_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasEnvelope()) {
        mergeEnvelope(other.getEnvelope());
      }
      if (other.getOk() != false) {
        setOk(other.getOk());
      }
      if (!other.getRejectCode().isEmpty()) {
        rejectCode_ = other.rejectCode_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              alias_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetEnvelopeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              ok_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              rejectCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object alias_ = "";
    /**
     * <code>string alias = 1 [json_name = "alias"];</code>
     * @return The alias.
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alias = 1 [json_name = "alias"];</code>
     * @return The bytes for alias.
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alias = 1 [json_name = "alias"];</code>
     * @param value The alias to set.
     * @return This builder for chaining.
     */
    public Builder setAlias(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alias_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string alias = 1 [json_name = "alias"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlias() {
      alias_ = getDefaultInstance().getAlias();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string alias = 1 [json_name = "alias"];</code>
     * @param value The bytes for alias to set.
     * @return This builder for chaining.
     */
    public Builder setAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alias_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.rtdp.proto.v1.SignalEnvelope envelope_;
    private com.google.protobuf.SingleFieldBuilder<
        com.rtdp.proto.v1.SignalEnvelope, com.rtdp.proto.v1.SignalEnvelope.Builder, com.rtdp.proto.v1.SignalEnvelopeOrBuilder> envelopeBuilder_;
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     * @return Whether the envelope field is set.
     */
    public boolean hasEnvelope() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     * @return The envelope.
     */
    public com.rtdp.proto.v1.SignalEnvelope getEnvelope() {
      if (envelopeBuilder_ == null) {
        return envelope_ == null ? com.rtdp.proto.v1.SignalEnvelope.getDefaultInstance() : envelope_;
      } else {
        return envelopeBuilder_.getMessage();
      }
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     */
    public Builder setEnvelope(com.rtdp.proto.v1.SignalEnvelope value) {
      if (envelopeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        envelope_ = value;
      } else {
        envelopeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     */
    public Builder setEnvelope(
        com.rtdp.proto.v1.SignalEnvelope.Builder builderForValue) {
      if (envelopeBuilder_ == null) {
        envelope_ = builderForValue.build();
      } else {
        envelopeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     */
    public Builder mergeEnvelope(com.rtdp.proto.v1.SignalEnvelope value) {
      if (envelopeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          envelope_ != null &&
          envelope_ != com.rtdp.proto.v1.SignalEnvelope.getDefaultInstance()) {
          getEnvelopeBuilder().mergeFrom(value);
        } else {
          envelope_ = value;
        }
      } else {
        envelopeBuilder_.mergeFrom(value);
      }
      if (envelope_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     */
    public Builder clearEnvelope() {
      bitField0_ = (bitField0_ & ~0x00000002);
      envelope_ = null;
      if (envelopeBuilder_ != null) {
        envelopeBuilder_.dispose();
        envelopeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     */
    public com.rtdp.proto.v1.SignalEnvelope.Builder getEnvelopeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetEnvelopeFieldBuilder().getBuilder();
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     */
    public com.rtdp.proto.v1.SignalEnvelopeOrBuilder getEnvelopeOrBuilder() {
      if (envelopeBuilder_ != null) {
        return envelopeBuilder_.getMessageOrBuilder();
      } else {
        return envelope_ == null ?
            com.rtdp.proto.v1.SignalEnvelope.getDefaultInstance() : envelope_;
      }
    }
    /**
     * <code>.rtdp.v1.SignalEnvelope envelope = 2 [json_name = "envelope"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.rtdp.proto.v1.SignalEnvelope, com.rtdp.proto.v1.SignalEnvelope.Builder, com.rtdp.proto.v1.SignalEnvelopeOrBuilder> 
        internalGetEnvelopeFieldBuilder() {
      if (envelopeBuilder_ == null) {
        envelopeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.rtdp.proto.v1.SignalEnvelope, com.rtdp.proto.v1.SignalEnvelope.Builder, com.rtdp.proto.v1.SignalEnvelopeOrBuilder>(
                getEnvelope(),
                getParentForChildren(),
                isClean());
        envelope_ = null;
      }
      return envelopeBuilder_;
    }

    private boolean ok_ ;
    /**
     * <pre>
     * envelope validated + status OK
     * </pre>
     *
     * <code>bool ok = 3 [json_name = "ok"];</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }
    /**
     * <pre>
     * envelope validated + status OK
     * </pre>
     *
     * <code>bool ok = 3 [json_name = "ok"];</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {

      ok_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * envelope validated + status OK
     * </pre>
     *
     * <code>bool ok = 3 [json_name = "ok"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ok_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object rejectCode_ = "";
    /**
     * <code>string reject_code = 4 [json_name = "rejectCode"];</code>
     * @return The rejectCode.
     */
    public java.lang.String getRejectCode() {
      java.lang.Object ref = rejectCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rejectCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reject_code = 4 [json_name = "rejectCode"];</code>
     * @return The bytes for rejectCode.
     */
    public com.google.protobuf.ByteString
        getRejectCodeBytes() {
      java.lang.Object ref = rejectCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rejectCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reject_code = 4 [json_name = "rejectCode"];</code>
     * @param value The rejectCode to set.
     * @return This builder for chaining.
     */
    public Builder setRejectCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rejectCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string reject_code = 4 [json_name = "rejectCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRejectCode() {
      rejectCode_ = getDefaultInstance().getRejectCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string reject_code = 4 [json_name = "rejectCode"];</code>
     * @param value The bytes for rejectCode to set.
     * @return This builder for chaining.
     */
    public Builder setRejectCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rejectCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rtdp.v1.ResolvedSignal)
  }

  // @@protoc_insertion_point(class_scope:rtdp.v1.ResolvedSignal)
  private static final com.rtdp.proto.v1.ResolvedSignal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rtdp.proto.v1.ResolvedSignal();
  }

  public static com.rtdp.proto.v1.ResolvedSignal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResolvedSignal>
      PARSER = new com.google.protobuf.AbstractParser<ResolvedSignal>() {
    @java.lang.Override
    public ResolvedSignal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResolvedSignal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResolvedSignal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rtdp.proto.v1.ResolvedSignal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

