// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/services.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface ResolveSignalsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.ResolveSignalsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 1 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string environment = 2 [json_name = "environment"];</code>
   * @return The environment.
   */
  java.lang.String getEnvironment();
  /**
   * <code>string environment = 2 [json_name = "environment"];</code>
   * @return The bytes for environment.
   */
  com.google.protobuf.ByteString
      getEnvironmentBytes();

  /**
   * <code>.rtdp.v1.Mode mode = 3 [json_name = "mode"];</code>
   * @return The enum numeric value on the wire for mode.
   */
  int getModeValue();
  /**
   * <code>.rtdp.v1.Mode mode = 3 [json_name = "mode"];</code>
   * @return The mode.
   */
  com.rtdp.proto.v1.Mode getMode();

  /**
   * <code>string transaction_id = 4 [json_name = "transactionId"];</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 4 [json_name = "transactionId"];</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>int64 transaction_revision = 5 [json_name = "transactionRevision"];</code>
   * @return The transactionRevision.
   */
  long getTransactionRevision();

  /**
   * <code>string decision_context_id = 6 [json_name = "decisionContextId"];</code>
   * @return The decisionContextId.
   */
  java.lang.String getDecisionContextId();
  /**
   * <code>string decision_context_id = 6 [json_name = "decisionContextId"];</code>
   * @return The bytes for decisionContextId.
   */
  com.google.protobuf.ByteString
      getDecisionContextIdBytes();

  /**
   * <code>.google.protobuf.Timestamp event_time = 7 [json_name = "eventTime"];</code>
   * @return Whether the eventTime field is set.
   */
  boolean hasEventTime();
  /**
   * <code>.google.protobuf.Timestamp event_time = 7 [json_name = "eventTime"];</code>
   * @return The eventTime.
   */
  com.google.protobuf.Timestamp getEventTime();
  /**
   * <code>.google.protobuf.Timestamp event_time = 7 [json_name = "eventTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder();

  /**
   * <code>int64 deadline_ms = 8 [json_name = "deadlineMs"];</code>
   * @return The deadlineMs.
   */
  long getDeadlineMs();

  /**
   * <code>repeated .rtdp.v1.SignalSpec specs = 9 [json_name = "specs"];</code>
   */
  java.util.List<com.rtdp.proto.v1.SignalSpec> 
      getSpecsList();
  /**
   * <code>repeated .rtdp.v1.SignalSpec specs = 9 [json_name = "specs"];</code>
   */
  com.rtdp.proto.v1.SignalSpec getSpecs(int index);
  /**
   * <code>repeated .rtdp.v1.SignalSpec specs = 9 [json_name = "specs"];</code>
   */
  int getSpecsCount();
  /**
   * <code>repeated .rtdp.v1.SignalSpec specs = 9 [json_name = "specs"];</code>
   */
  java.util.List<? extends com.rtdp.proto.v1.SignalSpecOrBuilder> 
      getSpecsOrBuilderList();
  /**
   * <code>repeated .rtdp.v1.SignalSpec specs = 9 [json_name = "specs"];</code>
   */
  com.rtdp.proto.v1.SignalSpecOrBuilder getSpecsOrBuilder(
      int index);

  /**
   * <pre>
   * Ordered feature vector for provider input construction.
   * </pre>
   *
   * <code>repeated string feature_names = 10 [json_name = "featureNames"];</code>
   * @return A list containing the featureNames.
   */
  java.util.List<java.lang.String>
      getFeatureNamesList();
  /**
   * <pre>
   * Ordered feature vector for provider input construction.
   * </pre>
   *
   * <code>repeated string feature_names = 10 [json_name = "featureNames"];</code>
   * @return The count of featureNames.
   */
  int getFeatureNamesCount();
  /**
   * <pre>
   * Ordered feature vector for provider input construction.
   * </pre>
   *
   * <code>repeated string feature_names = 10 [json_name = "featureNames"];</code>
   * @param index The index of the element to return.
   * @return The featureNames at the given index.
   */
  java.lang.String getFeatureNames(int index);
  /**
   * <pre>
   * Ordered feature vector for provider input construction.
   * </pre>
   *
   * <code>repeated string feature_names = 10 [json_name = "featureNames"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the featureNames at the given index.
   */
  com.google.protobuf.ByteString
      getFeatureNamesBytes(int index);

  /**
   * <code>repeated .rtdp.v1.TypedValue feature_values = 11 [json_name = "featureValues"];</code>
   */
  java.util.List<com.rtdp.proto.v1.TypedValue> 
      getFeatureValuesList();
  /**
   * <code>repeated .rtdp.v1.TypedValue feature_values = 11 [json_name = "featureValues"];</code>
   */
  com.rtdp.proto.v1.TypedValue getFeatureValues(int index);
  /**
   * <code>repeated .rtdp.v1.TypedValue feature_values = 11 [json_name = "featureValues"];</code>
   */
  int getFeatureValuesCount();
  /**
   * <code>repeated .rtdp.v1.TypedValue feature_values = 11 [json_name = "featureValues"];</code>
   */
  java.util.List<? extends com.rtdp.proto.v1.TypedValueOrBuilder> 
      getFeatureValuesOrBuilderList();
  /**
   * <code>repeated .rtdp.v1.TypedValue feature_values = 11 [json_name = "featureValues"];</code>
   */
  com.rtdp.proto.v1.TypedValueOrBuilder getFeatureValuesOrBuilder(
      int index);

  /**
   * <code>string input_snapshot_digest = 12 [json_name = "inputSnapshotDigest"];</code>
   * @return The inputSnapshotDigest.
   */
  java.lang.String getInputSnapshotDigest();
  /**
   * <code>string input_snapshot_digest = 12 [json_name = "inputSnapshotDigest"];</code>
   * @return The bytes for inputSnapshotDigest.
   */
  com.google.protobuf.ByteString
      getInputSnapshotDigestBytes();

  /**
   * <code>string traceparent = 13 [json_name = "traceparent"];</code>
   * @return The traceparent.
   */
  java.lang.String getTraceparent();
  /**
   * <code>string traceparent = 13 [json_name = "traceparent"];</code>
   * @return The bytes for traceparent.
   */
  com.google.protobuf.ByteString
      getTraceparentBytes();
}
