// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/services.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface ScoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.ScoreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rtdp.v1.SignalEnvelope envelope = 1 [json_name = "envelope"];</code>
   * @return Whether the envelope field is set.
   */
  boolean hasEnvelope();
  /**
   * <code>.rtdp.v1.SignalEnvelope envelope = 1 [json_name = "envelope"];</code>
   * @return The envelope.
   */
  com.rtdp.proto.v1.SignalEnvelope getEnvelope();
  /**
   * <code>.rtdp.v1.SignalEnvelope envelope = 1 [json_name = "envelope"];</code>
   */
  com.rtdp.proto.v1.SignalEnvelopeOrBuilder getEnvelopeOrBuilder();
}
