// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/services.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public final class ServicesProtos extends com.google.protobuf.GeneratedFile {
  private ServicesProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServicesProtos");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ScoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ScoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ScoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ScoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_WarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_WarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_WarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_WarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_FeatureRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_FeatureRef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ResolveFeaturesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ResolveFeaturesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ResolveFeaturesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ResolveFeaturesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ResolveFeaturesResponse_FeaturesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ResolveFeaturesResponse_FeaturesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_SignalSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_SignalSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ResolveSignalsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ResolveSignalsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ResolvedSignal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ResolvedSignal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_ResolveSignalsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_ResolveSignalsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_EvaluateRulesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_EvaluateRulesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_EvaluateRulesRequest_FeaturesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_EvaluateRulesRequest_FeaturesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_EvaluateRulesRequest_SignalsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_EvaluateRulesRequest_SignalsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_EvaluateRulesRequest_CfgEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_EvaluateRulesRequest_CfgEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_EvaluateRulesRequest_InputEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_EvaluateRulesRequest_InputEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_FiredRule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_FiredRule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_EvaluateRulesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_EvaluateRulesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_GetDecisionStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_GetDecisionStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rtdp_v1_GetDecisionStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rtdp_v1_GetDecisionStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026rtdp/v1/services.proto\022\007rtdp.v1\032\037googl" +
      "e/protobuf/timestamp.proto\032\026rtdp/v1/deci" +
      "sion.proto\032\026rtdp/v1/envelope.proto\"\224\006\n\014S" +
      "coreRequest\022\033\n\ttenant_id\030\001 \001(\tR\010tenantId" +
      "\022 \n\013environment\030\002 \001(\tR\013environment\022!\n\004mo" +
      "de\030\003 \001(\0162\r.rtdp.v1.ModeR\004mode\022%\n\016transac" +
      "tion_id\030\004 \001(\tR\rtransactionId\0221\n\024transact" +
      "ion_revision\030\005 \001(\003R\023transactionRevision\022" +
      ".\n\023decision_context_id\030\006 \001(\tR\021decisionCo" +
      "ntextId\022\035\n\nbinding_id\030\007 \001(\tR\tbindingId\022\'" +
      "\n\017binding_version\030\010 \001(\003R\016bindingVersion\022" +
      "\031\n\010model_id\030\t \001(\tR\007modelId\022#\n\rmodel_vers" +
      "ion\030\n \001(\tR\014modelVersion\022!\n\014model_digest\030" +
      "\013 \001(\tR\013modelDigest\0221\n\024preprocessing_dige" +
      "st\030\014 \001(\tR\023preprocessingDigest\0222\n\025input_s" +
      "napshot_digest\030\r \001(\tR\023inputSnapshotDiges" +
      "t\022#\n\rfeature_names\030\016 \003(\tR\014featureNames\022:" +
      "\n\016feature_values\030\017 \003(\0132\023.rtdp.v1.TypedVa" +
      "lueR\rfeatureValues\0229\n\nevent_time\030\020 \001(\0132\032" +
      ".google.protobuf.TimestampR\teventTime\022\037\n" +
      "\013deadline_ms\030\021 \001(\003R\ndeadlineMs\022 \n\013tracep" +
      "arent\030\022 \001(\tR\013traceparent\022\'\n\017contract_dig" +
      "est\030\023 \001(\tR\016contractDigest\"D\n\rScoreRespon" +
      "se\0223\n\010envelope\030\001 \001(\0132\027.rtdp.v1.SignalEnv" +
      "elopeR\010envelope\"\312\002\n\013WarmRequest\022\031\n\010model" +
      "_id\030\001 \001(\tR\007modelId\022#\n\rmodel_version\030\002 \001(" +
      "\tR\014modelVersion\022!\n\014model_digest\030\003 \001(\tR\013m" +
      "odelDigest\022!\n\014artifact_uri\030\004 \001(\tR\013artifa" +
      "ctUri\022.\n\023input_schema_digest\030\005 \001(\tR\021inpu" +
      "tSchemaDigest\0221\n\024preprocessing_digest\030\006 " +
      "\001(\tR\023preprocessingDigest\022\'\n\017output_contr" +
      "act\030\007 \001(\tR\016outputContract\022)\n\020contract_ve" +
      "rsion\030\010 \001(\tR\017contractVersion\"]\n\014WarmResp" +
      "onse\022\024\n\005ready\030\001 \001(\010R\005ready\022!\n\014model_dige" +
      "st\030\002 \001(\tR\013modelDigest\022\024\n\005error\030\003 \001(\tR\005er" +
      "ror\"N\n\nFeatureRef\022\022\n\004name\030\001 \001(\tR\004name\022\030\n" +
      "\007version\030\002 \001(\003R\007version\022\022\n\004tier\030\003 \001(\tR\004t" +
      "ier\"\325\003\n\026ResolveFeaturesRequest\022\033\n\ttenant" +
      "_id\030\001 \001(\tR\010tenantId\022 \n\013environment\030\002 \001(\t" +
      "R\013environment\022!\n\004mode\030\003 \001(\0162\r.rtdp.v1.Mo" +
      "deR\004mode\022%\n\016transaction_id\030\004 \001(\tR\rtransa" +
      "ctionId\0221\n\024transaction_revision\030\005 \001(\003R\023t" +
      "ransactionRevision\022-\n\022tokenized_claimant" +
      "\030\006 \001(\tR\021tokenizedClaimant\022\037\n\013provider_id" +
      "\030\007 \001(\tR\nproviderId\022\032\n\010currency\030\010 \001(\tR\010cu" +
      "rrency\022\026\n\006amount\030\t \001(\001R\006amount\0229\n\nevent_" +
      "time\030\n \001(\0132\032.google.protobuf.TimestampR\t" +
      "eventTime\022@\n\021required_features\030\013 \003(\0132\023.r" +
      "tdp.v1.FeatureRefR\020requiredFeatures\"\213\002\n\027" +
      "ResolveFeaturesResponse\022J\n\010features\030\001 \003(" +
      "\0132..rtdp.v1.ResolveFeaturesResponse.Feat" +
      "uresEntryR\010features\022)\n\020missing_features\030" +
      "\002 \003(\tR\017missingFeatures\022\'\n\017snapshot_diges" +
      "t\030\003 \001(\tR\016snapshotDigest\032P\n\rFeaturesEntry" +
      "\022\020\n\003key\030\001 \001(\tR\003key\022)\n\005value\030\002 \001(\0132\023.rtdp" +
      ".v1.TypedValueR\005value:\0028\001\"\272\004\n\nSignalSpec" +
      "\022\024\n\005alias\030\001 \001(\tR\005alias\022\032\n\010contract\030\002 \001(\t" +
      "R\010contract\022-\n\022accepted_contracts\030\003 \003(\tR\021" +
      "acceptedContracts\022\'\n\017contract_digest\030\004 \001" +
      "(\tR\016contractDigest\022\030\n\007binding\030\005 \001(\tR\007bin" +
      "ding\022%\n\016binding_digest\030\006 \001(\tR\rbindingDig" +
      "est\022\035\n\ntimeout_ms\030\007 \001(\003R\ttimeoutMs\022\032\n\010re" +
      "quired\030\010 \001(\010R\010required\022\032\n\010provider\030\t \001(\t" +
      "R\010provider\022!\n\014endpoint_ref\030\n \001(\tR\013endpoi" +
      "ntRef\022\024\n\005model\030\013 \001(\tR\005model\022!\n\014model_dig" +
      "est\030\014 \001(\tR\013modelDigest\022.\n\023input_schema_d" +
      "igest\030\r \001(\tR\021inputSchemaDigest\0221\n\024prepro" +
      "cessing_digest\030\016 \001(\tR\023preprocessingDiges" +
      "t\022$\n\016maximum_age_ms\030\017 \001(\003R\014maximumAgeMs\022" +
      "%\n\016input_features\030\020 \003(\tR\rinputFeatures\"\301" +
      "\004\n\025ResolveSignalsRequest\022\033\n\ttenant_id\030\001 " +
      "\001(\tR\010tenantId\022 \n\013environment\030\002 \001(\tR\013envi" +
      "ronment\022!\n\004mode\030\003 \001(\0162\r.rtdp.v1.ModeR\004mo" +
      "de\022%\n\016transaction_id\030\004 \001(\tR\rtransactionI" +
      "d\0221\n\024transaction_revision\030\005 \001(\003R\023transac" +
      "tionRevision\022.\n\023decision_context_id\030\006 \001(" +
      "\tR\021decisionContextId\0229\n\nevent_time\030\007 \001(\013" +
      "2\032.google.protobuf.TimestampR\teventTime\022" +
      "\037\n\013deadline_ms\030\010 \001(\003R\ndeadlineMs\022)\n\005spec" +
      "s\030\t \003(\0132\023.rtdp.v1.SignalSpecR\005specs\022#\n\rf" +
      "eature_names\030\n \003(\tR\014featureNames\022:\n\016feat" +
      "ure_values\030\013 \003(\0132\023.rtdp.v1.TypedValueR\rf" +
      "eatureValues\0222\n\025input_snapshot_digest\030\014 " +
      "\001(\tR\023inputSnapshotDigest\022 \n\013traceparent\030" +
      "\r \001(\tR\013traceparent\"\214\001\n\016ResolvedSignal\022\024\n" +
      "\005alias\030\001 \001(\tR\005alias\0223\n\010envelope\030\002 \001(\0132\027." +
      "rtdp.v1.SignalEnvelopeR\010envelope\022\016\n\002ok\030\003" +
      " \001(\010R\002ok\022\037\n\013reject_code\030\004 \001(\tR\nrejectCod" +
      "e\"K\n\026ResolveSignalsResponse\0221\n\007signals\030\001" +
      " \003(\0132\027.rtdp.v1.ResolvedSignalR\007signals\"\225" +
      "\006\n\024EvaluateRulesRequest\022%\n\016ruleset_diges" +
      "t\030\001 \001(\tR\rrulesetDigest\022*\n\021ruleset_spec_j" +
      "son\030\002 \001(\014R\017rulesetSpecJson\022G\n\010features\030\003" +
      " \003(\0132+.rtdp.v1.EvaluateRulesRequest.Feat" +
      "uresEntryR\010features\022D\n\007signals\030\004 \003(\0132*.r" +
      "tdp.v1.EvaluateRulesRequest.SignalsEntry" +
      "R\007signals\0224\n\026present_signal_aliases\030\005 \003(" +
      "\tR\024presentSignalAliases\0228\n\003cfg\030\006 \003(\0132&.r" +
      "tdp.v1.EvaluateRulesRequest.CfgEntryR\003cf" +
      "g\022>\n\005input\030\007 \003(\0132(.rtdp.v1.EvaluateRules" +
      "Request.InputEntryR\005input\022.\n\023execution_b" +
      "udget_ms\030\010 \001(\003R\021executionBudgetMs\032P\n\rFea" +
      "turesEntry\022\020\n\003key\030\001 \001(\tR\003key\022)\n\005value\030\002 " +
      "\001(\0132\023.rtdp.v1.TypedValueR\005value:\0028\001\032M\n\014S" +
      "ignalsEntry\022\020\n\003key\030\001 \001(\tR\003key\022\'\n\005value\030\002" +
      " \001(\0132\021.rtdp.v1.ValueMapR\005value:\0028\001\032K\n\010Cf" +
      "gEntry\022\020\n\003key\030\001 \001(\tR\003key\022)\n\005value\030\002 \001(\0132" +
      "\023.rtdp.v1.TypedValueR\005value:\0028\001\032M\n\nInput" +
      "Entry\022\020\n\003key\030\001 \001(\tR\003key\022)\n\005value\030\002 \001(\0132\023" +
      ".rtdp.v1.TypedValueR\005value:\0028\001\"X\n\tFiredR" +
      "ule\022\027\n\007rule_id\030\001 \001(\tR\006ruleId\022\032\n\010decision" +
      "\030\002 \001(\tR\010decision\022\026\n\006reason\030\003 \001(\tR\006reason" +
      "\"\310\001\n\025EvaluateRulesResponse\022(\n\005fired\030\001 \003(" +
      "\0132\022.rtdp.v1.FiredRuleR\005fired\022(\n\020skipped_" +
      "rule_ids\030\002 \003(\tR\016skippedRuleIds\022\032\n\010decisi" +
      "on\030\003 \001(\tR\010decision\022!\n\014reason_codes\030\004 \003(\t" +
      "R\013reasonCodes\022\034\n\tdefaulted\030\005 \001(\010R\tdefaul" +
      "ted\"V\n\030GetDecisionStatusRequest\022\033\n\ttenan" +
      "t_id\030\001 \001(\tR\010tenantId\022\035\n\nrequest_id\030\002 \001(\t" +
      "R\trequestId\"f\n\031GetDecisionStatusResponse" +
      "\0223\n\010decision\030\001 \001(\0132\027.rtdp.v1.DecisionRes" +
      "ultR\010decision\022\024\n\005found\030\002 \001(\010R\005found2\177\n\020I" +
      "nferenceService\0226\n\005Score\022\025.rtdp.v1.Score" +
      "Request\032\026.rtdp.v1.ScoreResponse\0223\n\004Warm\022" +
      "\024.rtdp.v1.WarmRequest\032\025.rtdp.v1.WarmResp" +
      "onse2f\n\016FeatureService\022T\n\017ResolveFeature" +
      "s\022\037.rtdp.v1.ResolveFeaturesRequest\032 .rtd" +
      "p.v1.ResolveFeaturesResponse2c\n\016SignalRe" +
      "solver\022Q\n\016ResolveSignals\022\036.rtdp.v1.Resol" +
      "veSignalsRequest\032\037.rtdp.v1.ResolveSignal" +
      "sResponse2^\n\014RulesService\022N\n\rEvaluateRul" +
      "es\022\035.rtdp.v1.EvaluateRulesRequest\032\036.rtdp" +
      ".v1.EvaluateRulesResponse2\260\001\n\014Orchestrat" +
      "or\022D\n\006Decide\022!.rtdp.v1.AuthenticatedTran" +
      "saction\032\027.rtdp.v1.DecisionResult\022Z\n\021GetD" +
      "ecisionStatus\022!.rtdp.v1.GetDecisionStatu" +
      "sRequest\032\".rtdp.v1.GetDecisionStatusResp" +
      "onseBQ\n\021com.rtdp.proto.v1B\016ServicesProto" +
      "sP\001Z*github.com/rtdp/rtdp/gen/go/rtdp/v1" +
      ";rtdpv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.rtdp.proto.v1.DecisionProtos.getDescriptor(),
          com.rtdp.proto.v1.Envelope.getDescriptor(),
        });
    internal_static_rtdp_v1_ScoreRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rtdp_v1_ScoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ScoreRequest_descriptor,
        new java.lang.String[] { "TenantId", "Environment", "Mode", "TransactionId", "TransactionRevision", "DecisionContextId", "BindingId", "BindingVersion", "ModelId", "ModelVersion", "ModelDigest", "PreprocessingDigest", "InputSnapshotDigest", "FeatureNames", "FeatureValues", "EventTime", "DeadlineMs", "Traceparent", "ContractDigest", });
    internal_static_rtdp_v1_ScoreResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rtdp_v1_ScoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ScoreResponse_descriptor,
        new java.lang.String[] { "Envelope", });
    internal_static_rtdp_v1_WarmRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rtdp_v1_WarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_WarmRequest_descriptor,
        new java.lang.String[] { "ModelId", "ModelVersion", "ModelDigest", "ArtifactUri", "InputSchemaDigest", "PreprocessingDigest", "OutputContract", "ContractVersion", });
    internal_static_rtdp_v1_WarmResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_rtdp_v1_WarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_WarmResponse_descriptor,
        new java.lang.String[] { "Ready", "ModelDigest", "Error", });
    internal_static_rtdp_v1_FeatureRef_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_rtdp_v1_FeatureRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_FeatureRef_descriptor,
        new java.lang.String[] { "Name", "Version", "Tier", });
    internal_static_rtdp_v1_ResolveFeaturesRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_rtdp_v1_ResolveFeaturesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ResolveFeaturesRequest_descriptor,
        new java.lang.String[] { "TenantId", "Environment", "Mode", "TransactionId", "TransactionRevision", "TokenizedClaimant", "ProviderId", "Currency", "Amount", "EventTime", "RequiredFeatures", });
    internal_static_rtdp_v1_ResolveFeaturesResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_rtdp_v1_ResolveFeaturesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ResolveFeaturesResponse_descriptor,
        new java.lang.String[] { "Features", "MissingFeatures", "SnapshotDigest", });
    internal_static_rtdp_v1_ResolveFeaturesResponse_FeaturesEntry_descriptor =
      internal_static_rtdp_v1_ResolveFeaturesResponse_descriptor.getNestedType(0);
    internal_static_rtdp_v1_ResolveFeaturesResponse_FeaturesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ResolveFeaturesResponse_FeaturesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rtdp_v1_SignalSpec_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_rtdp_v1_SignalSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_SignalSpec_descriptor,
        new java.lang.String[] { "Alias", "Contract", "AcceptedContracts", "ContractDigest", "Binding", "BindingDigest", "TimeoutMs", "Required", "Provider", "EndpointRef", "Model", "ModelDigest", "InputSchemaDigest", "PreprocessingDigest", "MaximumAgeMs", "InputFeatures", });
    internal_static_rtdp_v1_ResolveSignalsRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_rtdp_v1_ResolveSignalsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ResolveSignalsRequest_descriptor,
        new java.lang.String[] { "TenantId", "Environment", "Mode", "TransactionId", "TransactionRevision", "DecisionContextId", "EventTime", "DeadlineMs", "Specs", "FeatureNames", "FeatureValues", "InputSnapshotDigest", "Traceparent", });
    internal_static_rtdp_v1_ResolvedSignal_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_rtdp_v1_ResolvedSignal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ResolvedSignal_descriptor,
        new java.lang.String[] { "Alias", "Envelope", "Ok", "RejectCode", });
    internal_static_rtdp_v1_ResolveSignalsResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_rtdp_v1_ResolveSignalsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_ResolveSignalsResponse_descriptor,
        new java.lang.String[] { "Signals", });
    internal_static_rtdp_v1_EvaluateRulesRequest_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_rtdp_v1_EvaluateRulesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_EvaluateRulesRequest_descriptor,
        new java.lang.String[] { "RulesetDigest", "RulesetSpecJson", "Features", "Signals", "PresentSignalAliases", "Cfg", "Input", "ExecutionBudgetMs", });
    internal_static_rtdp_v1_EvaluateRulesRequest_FeaturesEntry_descriptor =
      internal_static_rtdp_v1_EvaluateRulesRequest_descriptor.getNestedType(0);
    internal_static_rtdp_v1_EvaluateRulesRequest_FeaturesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_EvaluateRulesRequest_FeaturesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rtdp_v1_EvaluateRulesRequest_SignalsEntry_descriptor =
      internal_static_rtdp_v1_EvaluateRulesRequest_descriptor.getNestedType(1);
    internal_static_rtdp_v1_EvaluateRulesRequest_SignalsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_EvaluateRulesRequest_SignalsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rtdp_v1_EvaluateRulesRequest_CfgEntry_descriptor =
      internal_static_rtdp_v1_EvaluateRulesRequest_descriptor.getNestedType(2);
    internal_static_rtdp_v1_EvaluateRulesRequest_CfgEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_EvaluateRulesRequest_CfgEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rtdp_v1_EvaluateRulesRequest_InputEntry_descriptor =
      internal_static_rtdp_v1_EvaluateRulesRequest_descriptor.getNestedType(3);
    internal_static_rtdp_v1_EvaluateRulesRequest_InputEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_EvaluateRulesRequest_InputEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_rtdp_v1_FiredRule_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_rtdp_v1_FiredRule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_FiredRule_descriptor,
        new java.lang.String[] { "RuleId", "Decision", "Reason", });
    internal_static_rtdp_v1_EvaluateRulesResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_rtdp_v1_EvaluateRulesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_EvaluateRulesResponse_descriptor,
        new java.lang.String[] { "Fired", "SkippedRuleIds", "Decision", "ReasonCodes", "Defaulted", });
    internal_static_rtdp_v1_GetDecisionStatusRequest_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_rtdp_v1_GetDecisionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_GetDecisionStatusRequest_descriptor,
        new java.lang.String[] { "TenantId", "RequestId", });
    internal_static_rtdp_v1_GetDecisionStatusResponse_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_rtdp_v1_GetDecisionStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rtdp_v1_GetDecisionStatusResponse_descriptor,
        new java.lang.String[] { "Decision", "Found", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.rtdp.proto.v1.DecisionProtos.getDescriptor();
    com.rtdp.proto.v1.Envelope.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
