// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/envelope.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface SignalQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.SignalQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string defaulted_features = 1 [json_name = "defaultedFeatures"];</code>
   * @return A list containing the defaultedFeatures.
   */
  java.util.List<java.lang.String>
      getDefaultedFeaturesList();
  /**
   * <code>repeated string defaulted_features = 1 [json_name = "defaultedFeatures"];</code>
   * @return The count of defaultedFeatures.
   */
  int getDefaultedFeaturesCount();
  /**
   * <code>repeated string defaulted_features = 1 [json_name = "defaultedFeatures"];</code>
   * @param index The index of the element to return.
   * @return The defaultedFeatures at the given index.
   */
  java.lang.String getDefaultedFeatures(int index);
  /**
   * <code>repeated string defaulted_features = 1 [json_name = "defaultedFeatures"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the defaultedFeatures at the given index.
   */
  com.google.protobuf.ByteString
      getDefaultedFeaturesBytes(int index);

  /**
   * <code>repeated string stale_features = 2 [json_name = "staleFeatures"];</code>
   * @return A list containing the staleFeatures.
   */
  java.util.List<java.lang.String>
      getStaleFeaturesList();
  /**
   * <code>repeated string stale_features = 2 [json_name = "staleFeatures"];</code>
   * @return The count of staleFeatures.
   */
  int getStaleFeaturesCount();
  /**
   * <code>repeated string stale_features = 2 [json_name = "staleFeatures"];</code>
   * @param index The index of the element to return.
   * @return The staleFeatures at the given index.
   */
  java.lang.String getStaleFeatures(int index);
  /**
   * <code>repeated string stale_features = 2 [json_name = "staleFeatures"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the staleFeatures at the given index.
   */
  com.google.protobuf.ByteString
      getStaleFeaturesBytes(int index);
}
