// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/envelope.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

/**
 * <pre>
 * ValueMap wraps a typed payload map so it can be nested inside a map field
 * (proto maps cannot nest directly).
 * </pre>
 *
 * Protobuf type {@code rtdp.v1.ValueMap}
 */
@com.google.protobuf.Generated
public final class ValueMap extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rtdp.v1.ValueMap)
    ValueMapOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ValueMap");
  }
  // Use ValueMap.newBuilder() to construct.
  private ValueMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ValueMap() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rtdp.proto.v1.Envelope.internal_static_rtdp_v1_ValueMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetValues();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rtdp.proto.v1.Envelope.internal_static_rtdp_v1_ValueMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rtdp.proto.v1.ValueMap.class, com.rtdp.proto.v1.ValueMap.Builder.class);
  }

  public static final int VALUES_FIELD_NUMBER = 1;
  private static final class ValuesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.rtdp.proto.v1.TypedValue>newDefaultInstance(
                com.rtdp.proto.v1.Envelope.internal_static_rtdp_v1_ValueMap_ValuesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.rtdp.proto.v1.TypedValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.rtdp.proto.v1.TypedValue> values_;
  private com.google.protobuf.MapField<java.lang.String, com.rtdp.proto.v1.TypedValue>
  internalGetValues() {
    if (values_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValuesDefaultEntryHolder.defaultEntry);
    }
    return values_;
  }
  public int getValuesCount() {
    return internalGetValues().getMap().size();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
   */
  @java.lang.Override
  public boolean containsValues(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetValues().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getValues() {
    return getValuesMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getValuesMap() {
    return internalGetValues().getMap();
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.rtdp.proto.v1.TypedValue getValuesOrDefault(
      java.lang.String key,
      /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetValues().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
   */
  @java.lang.Override
  public com.rtdp.proto.v1.TypedValue getValuesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> map =
        internalGetValues().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetValues(),
        ValuesDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> entry
         : internalGetValues().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
      values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, values__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rtdp.proto.v1.ValueMap)) {
      return super.equals(obj);
    }
    com.rtdp.proto.v1.ValueMap other = (com.rtdp.proto.v1.ValueMap) obj;

    if (!internalGetValues().equals(
        other.internalGetValues())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetValues().getMap().isEmpty()) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetValues().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rtdp.proto.v1.ValueMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rtdp.proto.v1.ValueMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rtdp.proto.v1.ValueMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rtdp.proto.v1.ValueMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rtdp.proto.v1.ValueMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ValueMap wraps a typed payload map so it can be nested inside a map field
   * (proto maps cannot nest directly).
   * </pre>
   *
   * Protobuf type {@code rtdp.v1.ValueMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rtdp.v1.ValueMap)
      com.rtdp.proto.v1.ValueMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rtdp.proto.v1.Envelope.internal_static_rtdp_v1_ValueMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rtdp.proto.v1.Envelope.internal_static_rtdp_v1_ValueMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rtdp.proto.v1.ValueMap.class, com.rtdp.proto.v1.ValueMap.Builder.class);
    }

    // Construct using com.rtdp.proto.v1.ValueMap.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableValues().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rtdp.proto.v1.Envelope.internal_static_rtdp_v1_ValueMap_descriptor;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ValueMap getDefaultInstanceForType() {
      return com.rtdp.proto.v1.ValueMap.getDefaultInstance();
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ValueMap build() {
      com.rtdp.proto.v1.ValueMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rtdp.proto.v1.ValueMap buildPartial() {
      com.rtdp.proto.v1.ValueMap result = new com.rtdp.proto.v1.ValueMap(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rtdp.proto.v1.ValueMap result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.values_ = internalGetValues().build(ValuesDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rtdp.proto.v1.ValueMap) {
        return mergeFrom((com.rtdp.proto.v1.ValueMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rtdp.proto.v1.ValueMap other) {
      if (other == com.rtdp.proto.v1.ValueMap.getDefaultInstance()) return this;
      internalGetMutableValues().mergeFrom(
          other.internalGetValues());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableValues().ensureBuilderMap().put(
                  values__.getKey(), values__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class ValuesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue> {
      @java.lang.Override
      public com.rtdp.proto.v1.TypedValue build(com.rtdp.proto.v1.TypedValueOrBuilder val) {
        if (val instanceof com.rtdp.proto.v1.TypedValue) { return (com.rtdp.proto.v1.TypedValue) val; }
        return ((com.rtdp.proto.v1.TypedValue.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.rtdp.proto.v1.TypedValue> defaultEntry() {
        return ValuesDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ValuesConverter valuesConverter = new ValuesConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder> values_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetValues() {
      if (values_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(valuesConverter);
      }
      return values_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder, com.rtdp.proto.v1.TypedValue, com.rtdp.proto.v1.TypedValue.Builder>
        internalGetMutableValues() {
      if (values_ == null) {
        values_ = new com.google.protobuf.MapFieldBuilder<>(valuesConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return values_;
    }
    public int getValuesCount() {
      return internalGetValues().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    @java.lang.Override
    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValues().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> getValuesMap() {
      return internalGetValues().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.rtdp.proto.v1.TypedValue getValuesOrDefault(
        java.lang.String key,
        /* nullable */
com.rtdp.proto.v1.TypedValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableValues().ensureBuilderMap();
      return map.containsKey(key) ? valuesConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    @java.lang.Override
    public com.rtdp.proto.v1.TypedValue getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> map = internalGetMutableValues().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return valuesConverter.build(map.get(key));
    }
    public Builder clearValues() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableValues().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    public Builder removeValues(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableValues().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue>
        getMutableValues() {
      bitField0_ |= 0x00000001;
      return internalGetMutableValues().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    public Builder putValues(
        java.lang.String key,
        com.rtdp.proto.v1.TypedValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableValues().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    public Builder putAllValues(
        java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValue> values) {
      for (java.util.Map.Entry<java.lang.String, com.rtdp.proto.v1.TypedValue> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableValues().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .rtdp.v1.TypedValue&gt; values = 1 [json_name = "values"];</code>
     */
    public com.rtdp.proto.v1.TypedValue.Builder putValuesBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.rtdp.proto.v1.TypedValueOrBuilder> builderMap = internalGetMutableValues().ensureBuilderMap();
      com.rtdp.proto.v1.TypedValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.rtdp.proto.v1.TypedValue.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.rtdp.proto.v1.TypedValue) {
        entry = ((com.rtdp.proto.v1.TypedValue) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.rtdp.proto.v1.TypedValue.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:rtdp.v1.ValueMap)
  }

  // @@protoc_insertion_point(class_scope:rtdp.v1.ValueMap)
  private static final com.rtdp.proto.v1.ValueMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rtdp.proto.v1.ValueMap();
  }

  public static com.rtdp.proto.v1.ValueMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValueMap>
      PARSER = new com.google.protobuf.AbstractParser<ValueMap>() {
    @java.lang.Override
    public ValueMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValueMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValueMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rtdp.proto.v1.ValueMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

