// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rtdp/v1/services.proto
// Protobuf Java Version: 4.33.1

package com.rtdp.proto.v1;

@com.google.protobuf.Generated
public interface WarmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rtdp.v1.WarmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model_id = 1 [json_name = "modelId"];</code>
   * @return The modelId.
   */
  java.lang.String getModelId();
  /**
   * <code>string model_id = 1 [json_name = "modelId"];</code>
   * @return The bytes for modelId.
   */
  com.google.protobuf.ByteString
      getModelIdBytes();

  /**
   * <code>string model_version = 2 [json_name = "modelVersion"];</code>
   * @return The modelVersion.
   */
  java.lang.String getModelVersion();
  /**
   * <code>string model_version = 2 [json_name = "modelVersion"];</code>
   * @return The bytes for modelVersion.
   */
  com.google.protobuf.ByteString
      getModelVersionBytes();

  /**
   * <code>string model_digest = 3 [json_name = "modelDigest"];</code>
   * @return The modelDigest.
   */
  java.lang.String getModelDigest();
  /**
   * <code>string model_digest = 3 [json_name = "modelDigest"];</code>
   * @return The bytes for modelDigest.
   */
  com.google.protobuf.ByteString
      getModelDigestBytes();

  /**
   * <pre>
   * s3:// or file:// for local dev
   * </pre>
   *
   * <code>string artifact_uri = 4 [json_name = "artifactUri"];</code>
   * @return The artifactUri.
   */
  java.lang.String getArtifactUri();
  /**
   * <pre>
   * s3:// or file:// for local dev
   * </pre>
   *
   * <code>string artifact_uri = 4 [json_name = "artifactUri"];</code>
   * @return The bytes for artifactUri.
   */
  com.google.protobuf.ByteString
      getArtifactUriBytes();

  /**
   * <code>string input_schema_digest = 5 [json_name = "inputSchemaDigest"];</code>
   * @return The inputSchemaDigest.
   */
  java.lang.String getInputSchemaDigest();
  /**
   * <code>string input_schema_digest = 5 [json_name = "inputSchemaDigest"];</code>
   * @return The bytes for inputSchemaDigest.
   */
  com.google.protobuf.ByteString
      getInputSchemaDigestBytes();

  /**
   * <code>string preprocessing_digest = 6 [json_name = "preprocessingDigest"];</code>
   * @return The preprocessingDigest.
   */
  java.lang.String getPreprocessingDigest();
  /**
   * <code>string preprocessing_digest = 6 [json_name = "preprocessingDigest"];</code>
   * @return The bytes for preprocessingDigest.
   */
  com.google.protobuf.ByteString
      getPreprocessingDigestBytes();

  /**
   * <code>string output_contract = 7 [json_name = "outputContract"];</code>
   * @return The outputContract.
   */
  java.lang.String getOutputContract();
  /**
   * <code>string output_contract = 7 [json_name = "outputContract"];</code>
   * @return The bytes for outputContract.
   */
  com.google.protobuf.ByteString
      getOutputContractBytes();

  /**
   * <code>string contract_version = 8 [json_name = "contractVersion"];</code>
   * @return The contractVersion.
   */
  java.lang.String getContractVersion();
  /**
   * <code>string contract_version = 8 [json_name = "contractVersion"];</code>
   * @return The bytes for contractVersion.
   */
  com.google.protobuf.ByteString
      getContractVersionBytes();
}
