apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: action-dispatcher
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/action-dispatcher
            digest: "sha256:42b3434552ee9ce60d75a144ed6d6f94c0ec8116a4bab0c2f85de93c5868099b"
          service:
            port: null
          envFromSecrets:
            - name: rtdp-db

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
