apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: action-dispatcher
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/action-dispatcher
            digest: "sha256:1d92358fc77e91aa856d9d4cd6fabcf312480906e162c26691f3e1ec36c13fc6"
          service:
            port: null
          envFromSecrets:
            - name: rtdp-db

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
