apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-registry
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/agent-registry
            digest: "sha256:ec0681e06d6c83785231f54d2edebdbfb92c92171aeced15e19ee29c9bbad4fc"
          service:
            port: 8090
          probe:
            httpPath: /healthz
          envFromSecrets:
            - name: rtdp-db

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
