apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-gateway
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/agent-gateway
            digest: "sha256:1c1a8b7288813d13de01dbecdf184fe9ba43ed7c5d265a8af017f974f24a65f3"
          service:
            port: 8096
          probe:
            httpPath: /healthz
          env:
            RTDP_AGENT_REGISTRY_ADDR: http://agent-registry.rtdp.svc.cluster.local:8090
            RTDP_INGRESS_ADDR: http://ingress.rtdp.svc.cluster.local:8080
            RTDP_APPROVAL_ADDR: http://approval-service.rtdp.svc.cluster.local:8095
          envFromSecrets:
            - name: rtdp-db

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
