apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-service
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/feature-service
            digest: "sha256:5084ddead8e84bd8eb3e62ff04c257ed51f857ead2f70e4d71ca6cff16447dc9"
          service:
            port: 50052
          env:
            RTDP_FEATURE_PORT: "50052"

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
