apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-service
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/inference-service
            digest: "sha256:ba6b1e6a9386bd550bbd46462697c3db9f377b10dab346f6e8527fac16fd992d"
          service:
            port: 50051
          env:
            RTDP_INFERENCE_PORT: "50051"
            RTDP_INFERENCE_WORKERS: "4"
          nodeSelector:
            rtdp.io/pool: cpu-inference
          tolerations:
            - key: rtdp.io/inference
              operator: Equal
              value: cpu
              effect: NoSchedule
          resources:
            requests: { cpu: 500m, memory: 1Gi }
            limits: { cpu: "2", memory: 2Gi }

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
