apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchestrator
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/orchestrator
            digest: "sha256:49ba1b7ae454a3a9a84599d0cd337bd15390b5dec27be7995b2431e370f9cb92"
          service:
            port: 50055
          env:
            RTDP_TXN_POOL: "16"
            RTDP_FEATURE_ADDR: feature-service.rtdp.svc.cluster.local:50052
            RTDP_RULES_ADDR: rules-service.rtdp.svc.cluster.local:50053
            RTDP_RESOLVER_ADDR: signal-resolver.rtdp.svc.cluster.local:50054
            RTDP_BUNDLE_DIR: /bundles
          bundleSync:
            enabled: true   # bucket value merged from sandbox.yaml
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
