apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rules-service
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/rules-service
            digest: "sha256:3292a7e11e7f548a90d50ba72e20a09736e4a7c8a3961e11344dee6c5b03062b"
          service:
            port: 50053
          env:
            RTDP_RULES_PORT: "50053"

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
