apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slm-service
  namespace: argocd
spec:
  project: rtdp
  sources:
    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      path: deploy/helm/rtdp-service
      helm:
        valueFiles:
          - $values/deploy/argocd/values/sandbox.yaml
        values: |
          image:
            repository: 079457921611.dkr.ecr.us-east-1.amazonaws.com/rtdp/slm-service
            digest: "sha256:abaac435b97dc8e8954237b18f2ac67f47eda2f4ffb65a84726aecfa28283b6f"
          service:
            port: 50056
          env:
            RTDP_SLM_PORT: "50056"
            RTDP_OLLAMA_ADDR: http://ollama.rtdp.svc.cluster.local:11434

    - repoURL: https://github.com/atulchhoda2019/rtdp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rtdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
