apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rtdp.saName" . }}
  labels: {{- include "rtdp.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/pod-identity-agent-inject: "true"
